const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=__dirname,out=path.join(root,'output/video-07'),evidence=path.resolve(root,'../../../Claude and OpenAI docs/Genesis-Knowledge/evidence/tutorial-video-7-20261003');
const ffmpeg=path.join(root,'vendor/imageio_ffmpeg/binaries',fs.readdirSync(path.join(root,'vendor/imageio_ffmpeg/binaries')).find(n=>n.endsWith('.exe')));
const data=JSON.parse(fs.readFileSync(path.join(root,'timeline-video7.json'))),final=path.join(out,data.filename),sourceOnly=process.argv.includes('--source');
function signal(file){const a=cp.spawnSync(ffmpeg,['-v','error','-i',file,'-vn','-ac','1','-ar','8000','-f','f32le','pipe:1'],{maxBuffer:400*1024*1024,windowsHide:true});if(a.status!==0)throw Error(a.stderr.toString());const buf=a.stdout,block=4000,result=[];for(let start=0;start<buf.length/4;start+=block){let sum=0,peak=0,n=Math.min(block,buf.length/4-start);for(let j=0;j<n;j++){let v=buf.readFloatLE((start+j)*4);sum+=v*v;peak=Math.max(peak,Math.abs(v));}result.push({start:start/8000,end:(start+n)/8000,rmsDb:20*Math.log10(Math.sqrt(sum/n)||1e-12),peakDb:20*Math.log10(peak||1e-12)});}return {duration:buf.length/4/8000,blocks:result};}
function loudness(file){const r=cp.spawnSync(ffmpeg,['-hide_banner','-i',file,'-vn','-af','loudnorm=I=-20:TP=-2:LRA=9:print_format=json','-f','null','-'],{encoding:'utf8',windowsHide:true});if(r.status!==0)throw Error(r.stderr);return JSON.parse(r.stderr.slice(r.stderr.lastIndexOf('{'),r.stderr.lastIndexOf('}')+1));}
fs.mkdirSync(evidence,{recursive:true});
if(sourceOnly){const s=signal(data.music);fs.writeFileSync(path.join(evidence,'source-music-analysis.json'),JSON.stringify({music:data.music,duration:s.duration,opening:s.blocks.slice(0,24),ending:s.blocks.slice(-24),loudness:loudness(data.music),interpretation:data.audio.rationale},null,2));console.log('Source music inspected: '+s.duration);}
else{const s=signal(final),plan=JSON.parse(fs.readFileSync(path.join(out,'audio-plan.json')));const joins=plan.joins.filter(j=>j.start<plan.total).map(j=>({...j,blocks:s.blocks.filter(b=>b.start>=j.start-2&&b.start<j.end+2)}));const interior=s.blocks.filter(b=>b.start>=4&&b.end<=plan.total-7);const silent=interior.filter(b=>b.rmsDb<-65);if(s.duration<plan.total-.05||silent.length)throw Error('Audio gap or short audio bed');const result={videoSha256:crypto.createHash('sha256').update(fs.readFileSync(final)).digest('hex'),duration:s.duration,plan,opening:s.blocks.slice(0,16),ending:s.blocks.slice(-20),joins,interiorSilentBlocks:silent.length,lowestInteriorRmsDb:Math.min(...interior.map(b=>b.rmsDb)),loudness:loudness(final),limitations:['Instrumented audio analysis and browser playback; no subjective continuous listening claim.']};fs.writeFileSync(path.join(evidence,'audio-analysis.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({duration:s.duration,joins:joins.length,silentBlocks:silent.length,loudness:result.loudness}));}

