/* Complete category 6: source-exact teaching, safe examples and owner checkpoints. */
const fs=require('fs'),path=require('path');const root=__dirname,catalog=JSON.parse(fs.readFileSync(path.resolve(root,'../tutorials/assets/scenes.json'))),ids=['memory','backup-data','activity','troubleshooting','system-pace','memory-options'],lessons=ids.map(id=>catalog.lessons.find(l=>l.id===id));
if(JSON.stringify(catalog.lessons.filter(l=>l.group==='care').sort((a,b)=>a.coursePosition-b.coursePosition).map(l=>l.id))!==JSON.stringify(ids))throw Error('Category changed');
const labels=['MEMORY','BACKUP & MOVE','ACTIVITY','TROUBLESHOOT','PACE & REST','MEMORY OPTIONS'],scenes=[];let chapter=0,lesson=null,step=null;
function add(kind,title,fields={},duration=24){const s={chapter,lesson:lesson?.id||null,sourceSteps:step?[step]:[],duration,kind,eyebrow:chapter?`${String(chapter).padStart(2,'0')} / ${labels[chapter-1]}${step?' · STEP '+step:''}`:'GENESIS AI · CATEGORY 6',title,...fields};scenes.push(s);return s}
function list(title,items,note='',duration=26){return add('list',title,{items,note},duration)}
function shot(title,body,g,note=''){return add('screen',title,{body,...g,note,contextZoom:false},26)}
const old=fs.readFileSync(path.join(root,'build-video5.cjs'),'utf8');eval(old.slice(old.indexOf('const {createCanvas'),old.indexOf('const titles=')).replace('function chunks','globalThis.chunks=function chunks'));
const titles={memory:['The thread and\nlasting memory','Ask clearly.\nCheck the result.','Browse and\nsearch memory','Health checks\nand upkeep','Protect the\nwhole store'],'backup-data':['Create, then\ncheck the result','Incomplete\nneeds attention','A copy outside\nthis computer','A package for\nthe new computer','Backup and\nrestore differ'],activity:['Your local\nactivity history','Three calendar\nviews','Reported and\nestimated counts','History and\ncurrent work'],troubleshooting:['Read the\nexact state','Check the\nmodel route','Listening or\nspeaking?','Check genuine\nimage support','Resume the\nintended task','Help with\nuseful evidence'],'system-pace':['Sleep is\nmaintenance','Zero means\nthe usual setting','Four different\npace controls','Thresholds and\nquiet hours','Steps for a\nturn or cycle','Finish, then\nwait or continue'],'memory-options':['Relevant recall\nhas a cost','Capacity and\nretention differ','What becomes\nlasting material','Organise\nrecent material','Plan an\nindex change','Optional\nadvanced tuning']};
const extra=JSON.parse(fs.readFileSync(path.join(root,'assets/video7/screens.json')));
function actual(name,match,{crop,highlight,callout}={}){const img=extra.screens[name];if(!img)throw Error('Missing '+name);const a=img.controls.find(c=>c.text===match||c.label===match)||img.controls.find(c=>new RegExp(match,'i').test([c.text,c.label].join(' ')));if(!highlight&&a)highlight=[a.x-a.w/2,a.y-a.h/2,a.w,a.h];if(!highlight)throw Error('No anchor '+name+' '+match);if(!crop){const [x,y,w,h]=highlight,cw=Math.min(img.width,Math.max(470,w+80)),ch=Math.min(img.height,Math.max(150,h+100));crop=[Math.max(0,Math.min(img.width-cw,x-40)),Math.max(0,Math.min(img.height-ch,y-50)),cw,ch]}return {screen:'@video7/'+name,crop,highlight,callout:callout||match}}
function region(name,match,top,height,label){return actual(name,match,{crop:[265,top,770,height],highlight:[280,top+15,735,height-35],callout:label||match})}
function original(s){const a=s.anchor,highlight=[a.x-a.width/2,a.y-a.height/2,a.width,a.height],w=Math.min(1500,Math.max(470,highlight[2]+80)),h=Math.min(450,Math.max(150,highlight[3]+100));return {screen:path.basename(s.screenshot,'.png'),crop:[Math.max(0,Math.min(1600-w,highlight[0]-40)),Math.max(0,Math.min(1000-h,highlight[1]-50)),w,h],highlight,callout:a.label}}
function geometry(s){switch(lesson.id){case 'memory':return [actual('memory-top','How Genesis remembers'),actual('memory-search','Demonstration: I prefer short shopping lists.',{crop:[265,285,540,95],highlight:[275,301,310,35],callout:'Labelled preference example'}),actual('memory-browse','Search',{crop:[260,150,670,115],highlight:[265,171,640,30],callout:'Search for a concrete phrase'}),region('health-ready','Health',204,170,'Health → Check'),region('backups-complete','Backups',204,230,'Complete result and archive list')][step-1];
case 'backup-data':return [region('backups-ready','Back up now',270,165,'Back up now, then wait for the result'),region('backups-incomplete','Backups',320,175,'Incomplete archive and previous complete copy'),region('backups-complete','Complete',330,100,'Identify the complete archive'),region('memory-top','Create transfer zip',280,190,'Transfer contents and import doorway'),region('backups-ready','Backups',204,135,'Restore script · Genesis closed')][step-1];
case 'activity':return [actual('activity-daily','Recording since',{crop:[425,190,980,300],highlight:[440,310,235,30],callout:'Local recording period'}),actual('activity-daily','Daily',{crop:[425,500,985,350],highlight:[1208,522,181,30],callout:'Daily · Weekly · Cumulative'}),actual('activity-daily','Input + output tokens',{crop:[425,365,985,130],highlight:[440,452,949,30],callout:'Provider reported · estimated'}),original(s)][step-1];
case 'system-pace':return [region('system-pace','Cognition speed & load',204,240,'Cognition speed & load'),region('system-pace','Cognitive load speed',270,115,'Zero · live effect · slider'),region('system-pace','Sleep length',380,335,'Tool load · sleep length · rest length'),region('system-thresholds','Cognitive thresholds',204,545,'Threshold · span · share · timing'),region('system-budgets','Mode step budgets',204,545,'Chat · Work · Autonomy steps'),region('system-budgets','Work policy',375,80,'Work policy: Managed or Continuous')][step-1];
case 'memory-options':return [region('memory-recall','Memory-first cognition',204,250,'Recall size and deliberate pacing'),region('memory-capacity','Memory tier caps',204,365,'Tier caps and temporary working notes'),region('memory-gate','Attention gate',204,115,'Gate threshold'),region('memory-consolidation','Consolidation & continuity',204,510,'Consolidation and idle Chat upkeep'),region('memory-embeddings','Embedding model',645,300,'Embedding model · dim · vector backend'),region('memory-dynamics','Criticality & edge dynamics',204,400,'Experimental advisory controls')][step-1];default:return original(s)}}
const examples={memory:[
['A fresh\nconversation',['New chat changes the visible thread','Selected memory can cross conversations','Experiences, facts and methods differ','Recall can be incomplete or mistaken'],'Example: a shopping-list preference can matter in a later chat. Starting that chat is separate from deleting memories.'],
['One useful\npreference',['Say: “Remember my short shopping lists”','Later ask which list style you prefer','Compare the actual recalled answer','Correct a specific wrong fact explicitly'],'This is an illustrative preference. The displayed memory is a clean fixture; no model recall result is claimed.'],
['Check a\nconcrete phrase',['Search for “shopping lists”','Read the result, not only its heading','A summary can omit original wording','Check whether old and new facts coexist'],'If a date was corrected, inspect which date is recalled. A new sentence does not automatically replace every similar record.'],
['A mistaken\nanswer',['Read the relevant memory first','Correct the specific fact clearly','Use Health → Check for store concerns','Keep defaults while you are learning'],'A read-only health check is upkeep. One wrong answer is not a reason to delete the store or start a migration.'],
['Before a\nlarger change',['Choose the Genesis backup controls','Wait for an explicitly complete result','Identify the matching complete archive','Protect that archive before moving data'],'A code snapshot protects a code folder. Genesis backup covers the app data supported by its backup system.']
], 'backup-data':[
['Read the\nfinished result',['Open Settings → Memory → Backups','Use Back up now on your intended store','Wait while the operation runs','Read “Backup complete” and its archive'],'The shown 1.2 MB archive and result are demonstration fixtures. They do not certify a real personal-data backup.'],
['Two ZIPs,\ndifferent status',['INCOMPLETE means the copy needs attention','The list marks the missing memory store','Keep the earlier complete archive','Try again when the system is idle'],'A file’s name or presence cannot establish completeness. Read the actual result and its list status.'],
['Protect against\na computer loss',['Identify a complete archive first','Check its complete displayed path','Copy it to storage you control elsewhere','Confirm the separate copy is present'],'Example folder: C:/Genesis-Practice/data/backups/\nArchive: genesis-practice-complete.zip.\nHover the archive row for its complete path.'],
['Plan the\ntransfer contents',['Read which personal data is included','Choose workspace files deliberately','Review encrypted-key handling separately','Import on the intended new installation'],'In this Windows UI, encrypted keys work for this Windows account; re-enter keys on another computer. No secrets are exported here.'],
['Plan a\nrestoration',['Identify the exact complete archive','Confirm the supported destination','Close Genesis before using the script','Get focused help if the process is unclear'],'Current panel names scripts/restore_backup.py. This tutorial does not restore a store or give a guessed personal-data command.']
],activity:[
['A local\nrecording period',['Read Recording since on the page','Inspect totals, duration and top tools','Earlier chats do not recreate old totals','Check when this version began recording'],'The captured date and small totals are labelled demonstration data. They are not the owner’s account history.'],
['A quiet day\nis ordinary',['Daily: inspect that day’s usage','Weekly: inspect its grouped week','Cumulative: inspect the running total','Click a day to read its detail'],'Current weekly grouping is Sunday–Saturday. A zero day can simply mean no recorded tasks ran.'],
['Read both\ncount labels',['Provider reported: supplied token counts','Estimated: inferred when counts are absent','Totals live on this computer','Account charges and quotas live with provider'],'The fixture shows 2,400 reported and 200 estimated tokens. Their sum is 2,600; neither number establishes remaining quota.'],
['Choose the\nright evidence',['Activity page: historical usage totals','Activity & context: current request state','System Feed and tool rows: what happened','Open the actual output to check success'],'An ended task, busy light, load value or low context number cannot prove that the requested result is correct.']
],troubleshooting:[
['One clear\nproblem statement',['Name the visible status or exact error','Say which action you just tried','Identify the selected model and route','Change one relevant thing at a time'],'Example: “After Send, the local model shows disconnected.” This is more useful than changing several unrelated settings.'],
['Local or\ncloud route?',['Local: service, address and model name','Local: enough available memory','Cloud: internet, key, access and quota','Read backup, step and context states'],'A backup may handle some provider failures. A turn step limit or full context calls for its own diagnosis.'],
['A short\nvoice test',['Recognition: mic, languages, Whisper size','Speech: engine, installed voice and key','Read separate microphone and speaker mutes','Try one short test after one change'],'If listening works but speech is silent, inspect speaking controls. Do not assume the microphone caused both problems.'],
['A simple\nimage first',['Read the actual Effective route','Check genuine primary or helper vision','Save an intended setting change','Try a simple image description'],'A text-only model needs a working image helper. A cloud helper needs its own valid connection. No live image test is claimed here.'],
['Continue the\nright work',['Read the plan and mission blocker','Answer the specific pending question','Resume the correct paused loop','Name the earlier task you want continued'],'Try “Continue the earlier task.” A new question may have a different purpose and need not restart old unfinished work.'],
['A useful\nhelp request',['Model and provider you selected','Exact error and steps already tried','Relevant tool output and visible state','Remove keys and unrelated personal details'],'Use Help index, How-to guides or Finish setting up. Before a repair involving personal data, make and verify a complete backup.']
], 'system-pace':[
['Read the\nstate and timer',['Continuous modes can rest or sleep','Upkeep can organise recent memory','The visible timer explains the pause','Chat waits for your messages'],'A mood or maintenance state describes software operation. It does not establish human feelings or successful work.'],
['Read each\nslider’s effect',['Zero is the usual setting','Each slider has a distinct purpose','Read its live effect before saving','Keep the working defaults to begin'],'A higher value is not automatically better. A pace change should answer an observed problem, not a general wish for more activity.'],
['Match control\nto observation',['Load speed: how quickly load builds','Tool load: failed tools and hard loops','Sleep length: the length of a sleep','Rest length: optional short micro-rests'],'Rest length matters when Take micro-rests is enabled. These four controls do not all change the same part of work.'],
['Separate\nsleep choices',['Threshold: when load triggers sleep','Span, share and max: work/sleep balance','Wake when rested: possible early wake','Quiet hours and micro-rests: separate'],'Read each explanation. Memory maintenance time and time working are a trade-off; defaults are a useful starting point.'],
['Steps and\naccount limits',['Chat budget: steps in one reply','Work or Autonomy: steps in a cycle','More steps can consume more tokens','New value applies next turn or cycle'],'The budget is separate from context size, provider rate limits and remaining account quota. An in-flight turn finishes safely.'],
['A bounded\nassignment',['Managed works on the assigned job','Once finished, it waits without inference','Continuous continues making useful work','Read the visible mode and saved policy'],'Choose the policy that matches your intention. Mission recovery settings belong to Missions separately.']
], 'memory-options':[
['Bring back\nrelevant material',['Recall refreshes memory during steps','Recalls per step sets how much returns','Pacing reminds it to reason from memory','More recall costs context and possibly time'],'Adding more memories is not a guarantee that the right fact will be found. Keep defaults until you can identify a specific need.'],
['Different\nstorage roles',['Episodic: remembered experiences','Semantic: facts and knowledge','Procedural: methods and skills','Working capacity and TTL: temporary notes'],'Capacity limits storage. Retention also depends on use, relevance and forgetting rules; a larger cap does not promise perfect recall.'],
['Selection and\nreinforcement',['Gate threshold concerns event salience','Less salient material can remain temporary','Flashbulb reinforcement resists pruning','Resistance is not permanence or perfection'],'Not every chat line becomes a lasting memory. Check actual saved or recalled material when the detail matters.'],
['Upkeep after\nrecent activity',['Consolidation groups and summarises','Continuity carries supported impressions','Idle Chat consolidation runs once per turn','LLM summaries can use the model'],'Continued idling does not endlessly repeat the same Chat consolidation. Leave budgets and similarity values at defaults while starting.'],
['An advanced\nsearch change',['Embeddings represent meaning as numbers','Model, dimension and backend work together','Old memories may need re-embedding','Plan a complete backup and Health checks'],'This field selects memory-search representation. It is separate from the chat model. No migration is performed in this tutorial.'],
['Observe before\nyou tune',['Criticality and moods are advisory','Boredom and wandering are experimental','Dream recombination is optional tuning','Check real behaviour over time'],'Defaults are the starting point. One deliberate change should have an observable purpose; it cannot guarantee a personality or reliability.']
]};
add('title','Keep Genesis\nyours.',{body:'Memory, complete backups and useful evidence.\nSix complete lessons, with the care and choices you keep.',tag:'VIDEO 7 · COMPLETE CATEGORY 6'},18);
for(let start=0;start<6;start+=3)list(start?'Diagnose and\nchoose a pace':'Care for\nyour Genesis',lessons.slice(start,start+3).map(l=>l.title),'Have Genesis open. Pause to practice. Screens show clean demonstration states; no personal data or live model result is shown.',26);
for(let n=0;n<6;n++){chapter=n+1;lesson=lessons[n];step=null;add('title',['Remember.\nCheck. Protect.','A complete copy.\nA planned move.','Usage you\ncan interpret.','One problem.\nUseful evidence.','Work, rest\nand your choice.','Gentle choices.\nWorking defaults.'][n],{body:lesson.title+'\n'+['Selected information, concrete checks and safe upkeep.','Completeness, separate storage, transfer and restore.','Recording period, calendar and count labels.','Visible state, connection routes and focused help.','Maintenance, pace controls and per-turn budgets.','Recall, retention, consolidation and search representation.'][n],tag:`LESSON ${n+1} OF 6`},18);list('Before\nyou begin',chunks(lesson.prerequisites,18),'Prepare these prerequisites before trying the lesson. Pause whenever you need time in Genesis.',24);
for(const s of lesson.steps){step=s.step;const blocks=lesson.id==='memory'&&step===2?['Try “Remember that I prefer short shopping lists.”','Later ask “What do you remember about how I like shopping lists?” For an important detail, check the saved or recalled result.','Correct a wrong fact explicitly: “That date is wrong; the correct date is…”']:chunks(s.narrationDraft),g=geometry(s);for(let j=0;j<blocks.length;j++)shot(titles[lesson.id][step-1],blocks[j],g,`Step ${step} of ${lesson.steps.length}${blocks.length>1?' · Teaching '+(j+1)+' of '+blocks.length:''}. ${j===0?'Locate the highlighted control.':'Read this distinction before acting.'}`);if(s.tip)list('A useful\ndetail',chunks(s.tip,22),'Keep this detail in mind as you practice.',24);const p=examples[lesson.id][step-1];list(p[0],p[1],p[2],28);
const supplement=(title,body,g,note)=>{for(const part of chunks(body))shot(title,part,g,note).supplemental=true};
if(lesson.id==='memory'&&step===2)add('quote','Try one\npreference',{quote:'Remember that I prefer short shopping lists.',body:'Later, ask what Genesis remembers about your shopping-list style. Compare its actual answer with the preference you intended.',note:'Illustrative wording only. The shown memory is a labelled fixture, not proof of a live model’s recall.'},28);
if(lesson.id==='memory'&&step===4)supplement('Read the\nhealth result','Check returns the supported read-only health rows. Read any failed row and keep its exact detail before planning a repair.',region('health-checked','Health',204,300,'Health result and supported checks'),'All checks passed is an isolated fixture. It does not certify the owner’s store or authorise deleting data.');
if(lesson.id==='backup-data'&&step===1)supplement('Complete is\nan explicit result','The current interface says “Backup complete” after a successful complete run, and marks its archive Complete. Read both the result and the intended archive.',region('backups-complete','Backups',320,115,'Backup complete · matching Complete archive'),'Clean 1.2 MB demonstration state. No real archive was created; a ZIP’s existence alone cannot certify completeness.');
if(lesson.id==='backup-data'&&step===2)supplement('Keep the earlier\ncomplete archive','The current list shows an incomplete archive separately from the previous complete one. The incomplete copy lacks the memory store.',region('backups-incomplete','Backups',320,175,'Incomplete — no memory store · Complete'),'Fixture rows only. Preserve the earlier complete backup and retry when idle; do not use the incomplete ZIP as a verified replacement.');
if(lesson.id==='backup-data'&&step===4)supplement('Read the\nkey handling','The current Windows checkbox explains that encrypted keys are usable by this Windows account. Re-enter keys on another computer. Decide separately whether to include workspace files.',region('memory-top','Create transfer zip',367,100,'Workspace and encrypted-key choices'),'No transfer package, import or secret copy is executed. Transfer and backup restore use different supported processes.');
if(lesson.id==='activity'&&step===2){supplement('Weekly groups\na week','Weekly groups the recorded days into a week. The current calendar uses Sunday–Saturday; selecting a day gives its week detail.',actual('activity-weekly','Weekly',{crop:[425,500,985,350],highlight:[1255,522,57,30],callout:'Weekly view'}),'Illustrative activity data. A quiet day is normal when no tasks ran.');supplement('Cumulative adds\nover time','Cumulative shows the lifetime total through each day. The selected-day detail keeps reported and estimated counts distinct.',actual('activity-detail','Cumulative',{crop:[425,500,985,440],highlight:[1313,522,77,30],callout:'Cumulative view and selected day'}),'Fixture totals, not a billing invoice or remaining quota. Recording begins with the feature’s version.');}
if(lesson.id==='system-pace'&&step===3)supplement('Four sliders,\nfour effects','Read Cognitive load speed, Tool load influence, Sleep length and Rest length as separate controls. Zero retains the usual setting for each.',region('system-pace','Cognition speed & load',270,440,'Four distinct pace sliders'),'These are captured defaults. No owner setting is changed or saved.');
if(lesson.id==='system-pace'&&step===4)supplement('Timing and\noptional rest','Wake when rested, Sleep in my quiet hours and Take micro-rests are independent choices. Read the explanation and preserve a working configuration before experimenting.',region('system-thresholds','Cognitive thresholds',600,185,'Wake when rested · quiet hours'),'Sleep and advisory mood do not prove feelings or task success. No setting is changed.');
if(lesson.id==='memory-options'&&step===2)supplement('Temporary notes\nand reinforcement','Working capacity limits temporary slots. Scratch note TTL controls fading working notes. Flashbulb threshold gives graded resistance to pruning.',region('memory-capacity','Memory tier caps',405,170,'Working capacity · TTL · flashbulb'),'Retention is separate from tier capacity. No setting can promise permanent, perfect recall.');
const check=list('Pause and\ncheck this',[s.checkpoint],'Try it in Genesis. Pause for as long as you need. Continue when you can explain or confirm this result.',22);check.checkpointSteps=[step];check.sourceSteps=[];
}step=null;list('Lesson\ncomplete',['Read the actual state and relevant result','Keep a complete backup for larger changes','Use one safe example at a time','Keep working defaults while learning'],'Return to any step using its lesson chapter. Use your own ordinary examples and pause whenever you need.',24);}
lesson=null;step=null;list('Your care\nchecklist',['Check the memory or recalled result you need','Verify backup completeness before a larger change','Keep a complete copy on separate storage','Read count labels and exact visible errors','Observe actual work before advanced tuning'],'All six lessons and all 32 steps of “Keep Genesis yours” are covered. The current course ends here.',31);add('title','Your Genesis.\nYour next step.',{body:'Return to a chapter whenever you need it.\nPause, practice and keep the choices that suit you.',tag:'SERIES COMPLETE · OWNER REVIEW'},20);
for(const s of scenes){const words=[s.title,s.body,s.note,s.quote,...(s.items||[])].filter(Boolean).join(' ').split(/\s+/).length;s.readingWords=words;s.readingSeconds=words/150*60;s.locateSeconds=s.kind==='screen'?7:4;s.duration=Math.max(s.duration,Math.ceil(s.readingSeconds+s.locateSeconds+3))}
const audio={repeatStart:8,trimEnd:237,crossfade:5,fadeIn:4,fadeOut:8,rationale:'Decoded 239.9335 s. Opening 0–8 s is quieter musical material near -22 to -18 dB RMS; retain it once. Established music begins at 8 s near -11 to -13 dB. Repeat 8–237 s, with equal-power 5 s joins across 232–237 s before the native ending drops to -30 dB at 237.5 s and below -63 dB at 239 s. Preserve natural internal dynamics; apply 4 s opening and 8 s closing fades only at video endpoints. Source -13.27 LUFS; final bed normalized toward -20 LUFS / -2 dBTP.'};
const data={title:'Keep Genesis yours',subtitle:'Complete category 6',music:'C:/Development-Gen/songs/video 1 song.MP3',outputFolder:'output/video-07',filename:'Genesis-Keep-Genesis-Yours.mp4',lessonIds:ids,chapters:['Introduction',...lessons.map(l=>l.title)],progressLabels:labels,sourceLessons:lessons,audio,scenes};fs.writeFileSync(path.join(root,'timeline-video7.json'),JSON.stringify(data,null,2));console.log(JSON.stringify({scenes:scenes.length,total:scenes.reduce((n,s)=>n+s.duration,0),steps:32,categories:[...new Set(catalog.lessons.map(l=>l.group))],lastLesson:catalog.lessons.at(-1).id}));
