/* Complete category 4; retain exact current-course teaching, tips and checkpoints. */
const fs=require('node:fs'),path=require('node:path');const root=__dirname;
const catalog=JSON.parse(fs.readFileSync(path.resolve(root,'../tutorials/assets/scenes.json'))),ids=['plan','modes-controls','projects','schedule','missions','mission-options'],lessons=ids.map(id=>catalog.lessons.find(l=>l.id===id));
if(JSON.stringify(catalog.lessons.filter(l=>l.group==='work').sort((a,b)=>a.coursePosition-b.coursePosition).map(l=>l.id))!==JSON.stringify(ids))throw Error('Category order changed');
const labels=['PLAN','MODES & CONTROLS','PROJECTS','SCHEDULE','MISSIONS','MISSION OPTIONS'];const scenes=[];let chapter=0,lesson=null,step=null;
function add(kind,title,fields={},duration=24){const s={chapter,lesson:lesson?.id||null,sourceSteps:step?[step]:[],duration,kind,eyebrow:chapter?`${String(chapter).padStart(2,'0')} / ${labels[chapter-1]}${step?' · STEP '+step:''}`:'GENESIS AI · CATEGORY 4',title,...fields};scenes.push(s);return s}
function list(title,items,note='',duration=26){return add('list',title,{items,note},duration)}
function compare(title,left,right,note=''){return add('compare',title,{cards:[{title:left[0],body:left[1],tag:left[2]||''},{title:right[0],body:right[1],tag:right[2]||''}],note},31)}
function shot(title,body,g,note=''){return add('screen',title,{body,...g,note,contextZoom:false},26)}
const {createCanvas,GlobalFonts}=require('C:/Users/damir/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');GlobalFonts.registerFromPath('C:/Windows/Fonts/segoeui.ttf','Genesis');const measure=createCanvas(10,10).getContext('2d');
function chunks(text,max=37){const width=max===37?678:810,size=max===37?40:33,allowed=max===37?5:2;measure.font=size+'px Genesis';const rows=t=>{let count=1,row='';for(const word of t.split(/\s+/)){const next=row?row+' '+word:word;if(measure.measureText(next).width>width&&row){count++;row=word}else row=next}return count};const sentences=text.split(/(?<=[.!?])\s+/);let out=[],current='';for(let sentence of sentences){sentence=sentence.trim();if(!sentence)continue;if(rows(sentence)>allowed){if(current){out.push(current);current=''}let part='';for(const word of sentence.split(/\s+/)){const next=(part+' '+word).trim();if(rows(next)>allowed&&part){out.push(part);part=word}else part=next}if(part)out.push(part)}else if(rows((current+' '+sentence).trim())>allowed){if(current)out.push(current);current=sentence}else current=(current+' '+sentence).trim()}if(current)out.push(current);return out}
const titles={plan:['Ask for\na plan','Read the\nstatus marks','Edit the\nworking plan','Explain the\nchanged goal'],'modes-controls':['Find the\nthree modes','Guide one\nexchange','Assign a\nclear job','Managed:\nfinish, then wait','Continuous:\nkeep helping','Autonomy:\nchoose activity','Match mode\nto intention','Pause and\nread','Resume\ndeliberately','Stop or\nStop All?','Other compact\ncontrols'],projects:['Open the\nproject board','Define the\nfinished result','Choose the\nwork model','Review the\nactual output'],schedule:['Describe the\ntimed job','Read the\nlocal time','Check model\nand tools','Result, start\nor notice?','Review, then\nCreate','Keep Genesis\nrunning'],missions:['Pieces that\nfit together','Answer the\ninterview','Choose the\nrole models','Agree, then\nsign','A graph from\nyour contract','Read each\ntask state','Dependencies\ncome first','Produce, then\nverify','Repair or\nchange route','Recoverable\ncheck-ins','When it\nneeds you','Steer the\nmission','Mission Pause\nand Abort','Progress and\nevidence','Your final\nacceptance'],'mission-options':['Specific\nrecovery choices','Smaller jobs\nfor local models','Models for\neach role','Useful source\nreading','A limit is not\npermission']};
function geometry(s){const a=s.anchor;let screen=path.basename(s.screenshot,'.png'),highlight=[a.x-a.width/2,a.y-a.height/2,a.width,a.height],callout=a.label,crop;
const override=(sc,c,h,label)=>{screen=sc;crop=c;highlight=h;callout=label};
if(lesson.id==='plan'){if(step===1||step===4)override('@video5/chat-modern',[365,935,180,65],[375.5,954.5,37,27],'Plan: show or collapse the checklist');else override('@video5/plan-hover',[370,80,520,145],step===2?[383,122,450,56]:[383,122,450,93],step===2?'Done, in progress, pending · completed count':'Click text or status · Add a step');}
if(lesson.id==='modes-controls'){
 if(step===1)override('chat-modern',[825,30,215,62],[866,40,108,30],'Speech bubble · briefcase · orbit');
 if(step===2)override('@video5/chat-modern',[360,855,600,100],[371,869,565,38],'Write the request in the message field');
 if(step===3)override('modern-work-managed',[825,30,550,62],[866,40,108,30],'Choose Work; its policy switch appears');
 if(step===4||step===5)override(step===4?'modern-work-managed':'modern-work-continuous',[1110,30,230,62],[1245,45,36,20],step===4?'Managed: assigned work, then wait':'Continuous: assigned work first, then more');
 if(step===6)override('modern-autonomy',[825,30,215,62],[942,40,32,30],'Autonomy: self-directed activity within permissions');
 if(step===10||step===11)override('@video5/chat-modern',[1280,936,208,64],step===10?[1346,954,58,28]:[1406,954,58,28],step===10?'Stop current reply · Stop all work':'Consolidate memories · Override current action');
}
if(screen==='project-new'){if(step===2){crop=[580,280,440,220];highlight=[597,312,406,168];callout='Title and description: define the result'}else{crop=[580,550,440,95];highlight=[597,586,406,36];callout='Work model and Work reasoning'}}
if(screen==='schedule-new'){crop=step===1?[545,265,510,175]:[545,490,510,100];if(step===1)highlight=[565,292,470,130];if(step===2){highlight=[565,518,470,36];callout='Start and end: read the local time'}if(step===5){crop=[545,655,510,125];highlight=[565,683,470,90];callout='Recurrence and Create: check before saving'}}
if(screen==='schedule-point'){crop=step===4?[545,525,510,170]:[545,755,510,135];highlight=step===4?[565,556,470,100]:[565,780,470,91];callout=step===4?'Point action and preparation estimate':'Recurrence, then Create';}
if(lesson.id==='schedule'&&step===3){screen='schedule-point';crop=[545,680,510,85];highlight=[565,712,470,36];callout='Model and reasoning for Work execution';}
if(screen==='mission-graph'){crop=[515,540,520,235];highlight=[535,575,480,186];callout=step===5?'Planner graph: an indented task list':step===14?'Task states and retained route history':s.anchor.label;}
if(screen==='mission-interview'){crop=[515,205,760,270];highlight=[536,264,700,143];callout='Answer before agreeing on the contract'}
if(screen==='mission-contract'){crop=[515,70,750,410];highlight=[536,110,710,358];callout='Read acceptance checks and allowed actions'}
if(screen==='mission-models'){crop=[265,345,765,355];highlight=[280,365,734,330];callout='Default, per-role and backup selections'}
if(screen==='mission-blocker'){crop=[515,330,760,180];highlight=[535,347,715,131];callout='Your answer · Approve / Done · Can’t'}
if(screen==='mission-signoff'){crop=[515,330,760,175];highlight=[536,342,710,145];callout='USER_SIGNOFF: inspect, then decide'}
if(screen==='mission-recovery'){crop=step===12?[590,75,385,65]:[525,135,510,195];highlight=step===12?[603.5,87,362,30]:[531,173,386,150];callout=step===12?'Adapt plan · Council · Edit contract':'Recovery options, then Save mission behavior'}
if(screen==='missions-settings'){if(step===1){crop=[265,530,765,95];highlight=[744,559,269,36];callout='Recoverable check-ins: choose the policy'}if(step===2){crop=[265,810,765,170];highlight=[706,859,308,36];callout='Worker leaf size: maximum assignment size'}if(step===5){crop=[265,425,765,70];highlight=[280,430,738,50];callout='Mission Payment Authority: dedicated setup'}}
if(!crop){const w=Math.min(1500,Math.max(430,highlight[2]+80)),h=Math.min(450,Math.max(125,highlight[3]+100));crop=[Math.max(0,Math.min(1600-w,highlight[0]-40)),Math.max(0,Math.min(1000-h,highlight[1]-50)),w,h]}
return {screen,crop,highlight,callout};}
const practice={
plan:[
['Plan before\nfile changes',['Ask: “Show me the plan before changing files.”','Name the folder you intend to organise','Say what the finished folder should contain','Read the proposed steps before proceeding'],'A useful plan describes both the order and the intended result. Use a small practice folder.'],
['A checklist\nexample',['Done: read the garden notes','In progress: draft the watering chart','Pending: compare the chart with the notes','Open the chart before accepting it'],'A checked item is a work-tracking claim. Compare the actual file with the original notes.'],
['Four ways\nto edit',['Click task text to revise the wording','Click a status dot to cycle its state','Use move up/down to change the order','Remove a step or use Add a step…'],'Edits target the active channel. Changing a status manually does not perform the underlying work.'],
['Preserve the\noriginals',['Pause if the correction must come first','Send: “Keep originals; make copies instead.”','Revise the corresponding plan item','Read the updated plan before resuming'],'The message explains the new goal. A checkbox alone cannot explain why you changed it.']
],
'modes-controls':[
['Recognise the\nthree icons',['Speech bubble: Chat','Briefcase: Work','Orbit: Autonomy','Hover for the exact name and explanation'],'Look at the selected button. Classic offers written names for the same companion choices.'],
['A guided\nconversation',['Send a short letter you may share','Ask for a plain-language explanation','Read the answer and tool activity','Ask your next question when ready'],'Chat may use tools for your request. It then waits for your next exchange.'],
['A small\nassigned project',['Create “Garden watering chart” in To Do','Supply the notes it should use','Specify the file and what counts as finished','Choose Work and inspect the policy switch'],'An assignment needs files, boundaries and a checkable result. A mode button alone does not supply the job.'],
['A stopping\nboundary',['Choose Managed','Let it work on eligible assignments','Read the result when it reaches Review','Expect waiting when assigned work runs out'],'Managed can take many tool steps. Your inspection still decides whether the result is acceptable.'],
['Ongoing\nassistance',['Choose Continuous deliberately','Assigned work still comes first','Inspect any newly proposed useful project','Return to Managed when that is your intent'],'Continuous may propose and prepare more work. Publishing, purchases and acceptance retain their own authority.'],
['Read what\nit actually does',['Begin with a limited set of tools','Choose Autonomy for open-ended exploration','Read the feed, plan and created outputs','Pause to inspect or redirect its activity'],'Mood, energy and rest are software state. Evaluate the visible activity and the results.'],
['Choose for\nyour intention',['Chat: guide each exchange','Work Managed: assigned jobs, then wait','Work Continuous: jobs, then more useful work','Autonomy: choose its own activity'],'Missions are a separate agreed process with contract, dependencies and verification.'],
['Pause is\ntime to inspect',['Locate Pause while work is running','Click it when you need reading time','Read the confirmed paused state','Inspect what has already happened'],'Pause does not undo a saved file, a submitted action or any other completed effect.'],
['Correct, then\ncontinue',['Read the unfinished job while paused','Send your changed goal clearly','Use Resume when you are ready','Confirm the resumed state'],'Changing companion mode can cancel or redirect work. Pause and inspect first when preserving context matters.'],
['Choose the\nright stop',['Stop: end current companion activity','State remains available for later','Stop All: stronger companion reset and mood reset','Mission Pause and Abort live inside Missions'],'Hover the Modern icons to read their labels. Check the resulting state after your action.'],
['Ordinary chat\nneeds neither',['Consolidate organises recent material into memory','Override manually addresses state constraints','Read tool permissions in Settings','Use these controls only when you understand why'],'Keep a routine chat simple: send, read, follow up. An override is not a routine permission shortcut.']
],
projects:[
['Read the\nboard stages',['Backlog: an idea for later','To Do: ready assigned work','In Progress: work underway','Review: inspect; Complete: accepted on the board'],'Begin with one small project. Status describes workflow; it does not certify every fact.'],
['A clear\ninvitation job',['Title: “Birthday invitation draft”','Output: a short editable invitation file','Supply date, venue and reply details','Boundary: draft only; do not send it'],'Specify the intended folder. Genesis cannot reliably guess missing event facts.'],
['A model\nthat fits',['Use the project’s execution fields if needed','Otherwise it inherits companion configuration','Keep a local-model assignment narrow','Check intended model and reasoning'],'A harder job may benefit from a more capable model. The result must still be easy to inspect.'],
['Accept after\ninspection',['Open the actual invitation file','Check date, place and reply details','Request a revision if something is wrong','Accept when it meets your stated result'],'Review and Complete are board stages. They do not automatically make generated facts true.']
],
schedule:[
['Describe the\ndelivery',['Example: “Prepare a watering summary.”','Name the notes and output destination','Say what the summary must contain','Start with a harmless test task'],'The schedule supplies timing. The instructions supply the job and a checkable result.'],
['Check every\ntime field',['Read the displayed local date and time','For repeats, describe what to do on each run','Ask it to recheck facts that can change','Confirm the saved schedule matches your intent'],'Do not carry a fixed old date into a repeating task that needs current information.'],
['Resources\nare prerequisites',['Work duration exposes model and reasoning','Autonomy duration follows its mode configuration','Preparation may expose Work execution settings','Check files, credentials and tool connections'],'A cloud model needs internet. Offline local work still needs its installed model and required material.'],
['Three different\npromises',['Deliver At: prepare early; hold until due time','Start At: begin the work at that time','Notify At: give the scheduled notice','For delivery, give a realistic preparation estimate'],'Example: a 17:00 result differs from starting the job at 17:00. A notice is not a prepared report.'],
['Read, then\nCreate',['Use once-only for a single event','Choose the intended recurrence for repeats','Check title, instructions, time and action','Click Create and find the saved item'],'Cancel closes this new-task editor. Test one small run before trusting a repeating routine.'],
['Check the\nactual result',['Keep the computer and backend running','Inspect output and recorded activity after due time','Check incomplete or failed work honestly','Pause or disable unwanted repeats'],'A saved local schedule cannot execute on a powered-off computer. Timing is best effort in an available process.']
],
missions:[
['One objective,\nseveral pieces',['Compare three weekend destinations','Collect travel and lodging prices','Build a budget table with source links','Check it against agreed acceptance conditions'],'This is an illustrative job. Compare only; no booking, payment or live mission runs in this video.'],
['Facts it\ncannot guess',['Say who is travelling and from where','Provide dates and the budget','Attach useful source documents','State: “Compare only; do not book anything.”'],'Answer the interview before agreeing on a contract. Missing facts can affect every later task.'],
['Four core\nroles',['Planner: divide the agreed job','Worker: produce one assigned piece','Verifier: check that piece and evidence','CEO: oversee the mission'],'One suitable model can fill several roles. Mission role backups are distinct from the companion backup.'],
['Make success\ncheckable',['Compare three named destinations','Include travel, lodging and source links','Check the budget and allowed actions','Edit vague conditions before signing'],'Signing starts planning for the agreed job. It does not make final acceptance automatic.'],
['A recipe-like\norder',['Gather travel prices with sources','Gather lodging prices for the same dates','Build the table from checked inputs','Check the table before final delivery'],'The Planner generates the graph. Dependencies run forward; the interface shows an indented task list.'],
['Six task\nstates',['Pending or ready: waiting versus eligible','Running: a Worker is doing the piece','awaiting_verify: submitted, not yet checked','Done: passed; obsolete: retained old route'],'Read the words and history as well as colours. An indented task belongs to a larger phase.'],
['Why the\ntable waits',['Travel prices are done','Lodging prices await verification','The table needs both checked inputs','Another ready branch may be eligible'],'Worker → Verifier → next Worker is sequential. Ready branches do not mean concurrent Workers.'],
['A separate\ncheck of the file',['Worker submits output and evidence','Fresh Verifier inspects the task checks','A pass can unlock dependent work','A failure returns to recovery'],'Model verification can help catch mistakes. Inspect the actual delivery and sources yourself too.'],
['Recover the\napproach',['Retry a recoverable attempt or request rework','Investigate failure and split an oversized task','Replan the affected branch if needed','Use the configured role backup for model trouble'],'Provider outage differs from an impossible objective. Recovery retains failures and replaced-task history.'],
['Choose recovery\ndeliberately',['Off: recoverable judgments can wait for you','On: let CEO decide, then continue','Or choose always replan and continue','Use Save mission behavior'],'The CEO has a bounded recovery scope. Final acceptance, conditions and new permissions still need their proper authority.'],
['A blocker\nneeds your answer',['Read the exact missing fact or action','Provide travel dates if you know them','Use Approve / Done only after doing it','Use Can’t and explain when you cannot help'],'Read WAITING_USER’s reason. Put private credentials in the supported secure entry flow.'],
['Three distinct\nsteering choices',['Adapt plan: change the route, such as train travel','Ask the council: request strategic review','Edit contract: change the job or its authority','Read new tasks and the ledger afterwards'],'Retired branches remain history. A route correction and a changed acceptance condition are different decisions.'],
['Controls inside\nthe mission',['Mission Pause: time to inspect or redirect','Resume from the mission when ready','Mission Abort: end this mission','Read the resulting mission status'],'Companion mode and Stop controls are separate. Mission Pause also cannot undo completed effects.'],
['Saved structure,\nwith limits',['Inspect contract and acceptance progress','Read task states, evidence and event history','Eligible saved progress can recover after restart','Check effects near an interrupted tool action'],'Unsaved thinking is not restored. An action may have happened before interruption was recorded.'],
['Your final\ndecision',['Wait for final verification and USER_SIGNOFF','Open the actual deliverables and source links','Check every agreed condition','Accept or explain the remaining revision'],'Checked tasks show progress. Only the owner can accept the whole delivery; recovery cannot waive this step.']
],
'mission-options':[
['Recovery has\na defined scope',['Ask the owner about recoverable judgments','Or use deterministic retry/replanning','Or give CEO a bounded attempt, then continue','Inspect the running mission’s own policy'],'No recovery choice grants credentials, spending authority, waived criteria or final acceptance.'],
['A smaller\nWorker leaf',['Choose S when broad tasks overwhelm a local model','Break a large phase into small assignments','Keep each output and check narrow','Read execution floor separately from size'],'The execution floor is a minimum step budget. It is not the task’s estimated size or a guarantee of success.'],
['The remaining\nroles',['Intake handles the interview','Council gives strategic review','Auditor offers independent review','Contract choices can override mission Settings'],'Planner, Worker, Verifier and CEO retain their own jobs. Strategic concurrency keeps Worker/Verifier sequential.'],
['Inspect source\nreading first',['Check what text was extracted','Read activity for slices or missing pages','Page a large document when needed','Keep reading useful within the model’s context'],'Increasing every limit consumes context and may not repair a missed document. Diagnose the actual reading route.'],
['Budget and\nauthority differ',['A cost envelope records a planned limit','Real payment needs dedicated signed policy','It also needs enabled path and verified connection','A no-funds test adapter cannot buy anything'],'Leave payment authority off unless you intend its supported setup. No purchase is run or authorised by this example.']
]};
add('title','Turn ideas into\nfinished work.',{body:'Plans, projects, schedules and Missions.\nSix complete lessons, with the controls and decisions you keep.',tag:'VIDEO 5 · COMPLETE CATEGORY 4'},18);
list('From a plan\nto a result',lessons.slice(0,3).map(l=>l.title),'Have Genesis open. Pause to practice. Screenshots use clean demonstration data; examples are not live model results.',30);
list('Timed work\nand Missions',lessons.slice(3).map(l=>l.title),'Pause to practice each example. Check the actual output before deciding that the job is finished.',26);
compare('Progress and\nacceptance',['PROGRESS','A plan mark, board stage or verified task helps you follow the work. It tells you where the process has reached.','READ THE STATE'],['ACCEPTANCE','Open the actual output and compare it with the result you agreed. Request revision when a condition is missing.','CHECK THE RESULT'],'Use clear goals, available material and the control that governs the process you intend to change.');
for(let n=0;n<lessons.length;n++){chapter=n+1;lesson=lessons[n];step=null;
add('title',['A plan\nyou can steer.','Choose how\nwork proceeds.','From idea\nto Review.','The right job.\nAt the right time.','A bigger job,\nin checked pieces.','Fit the mission\nto the model.'][n],{body:lesson.title+'\n'+['Track, edit and explain a changed goal.','Chat, Managed Work, Continuous Work and Autonomy.','Clear instructions, intended models and your inspection.','Local time, execution resources and three point actions.','Interview, contract, dependencies, recovery and your sign-off.','Smaller tasks, role models, source reading and authority.'][n],tag:`LESSON ${n+1} OF 6`},18);
list('Before\nyou begin',chunks(lesson.prerequisites,18),'Prepare these prerequisites before trying the lesson. Pause whenever you need time in Genesis.',24);
for(const s of lesson.steps){step=s.step;const blocks=chunks(s.narrationDraft),g=geometry(s);for(let j=0;j<blocks.length;j++)shot(titles[lesson.id][step-1],blocks[j],g,`Step ${step} of ${lesson.steps.length}${blocks.length>1?' · Teaching '+(j+1)+' of '+blocks.length:''}. ${j===0?'Locate the highlighted control.':'Read this distinction before acting.'}`);
if(lesson.id==='modes-controls'&&step===1)for(const [name,label,title]of [['chat','Chat','Chat — Talk with Genesis. Replies to your messages.'],['work','Work','Work mode — click to start Work'],['autonomy','Autonomy','Autonomy — Let Genesis choose and pursue its own activities.']])shot('Hover to\nread the name',title,{screen:'@video5/hover-'+name,crop:[850,30,140,65],highlight:[name==='chat'?866:name==='work'?904:942,40,32,30],callout:label+' icon'},'The text at left reproduces the current control’s hover title. The highlighted icon shows where to find it.').supplemental=true;
if(lesson.id==='plan'&&step===3)shot('Move or\nremove a step','Hover a plan row to reveal Move up, Move down and Remove step. Change the order when the work needs a different sequence.',{screen:'@video5/plan-hover',crop:[1380,110,90,55],highlight:[1405,121,52,16],callout:'Move up · Move down · Remove'},'These controls revise the checklist. They do not perform or reverse the work.').supplemental=true;
if(lesson.id==='projects'&&step===1)shot('Five board\nstages','Read the columns from left to right: Backlog, To Do, In Progress, Review and Complete. Place a ready assignment in To Do.',{screen:'projects',crop:[255,135,1345,90],highlight:[270,145,1290,40],callout:'Backlog → To Do → In Progress → Review → Complete'},'The explanatory cards name the stages clearly. The board’s status does not certify the output.').supplemental=true;
if(lesson.id==='missions'&&step===4)shot('Save, then\nsign the agreement','At the bottom of the contract, read any validation message. Save your edits and use Sign & start only when the objective, checks and authority match your intent.',{screen:'@video5/mission-sign',crop:[510,930,350,65],highlight:[519,946,197,32],callout:'Save draft · Sign & start'},'A demonstration contract, with no real mission started. Signing begins planning; final acceptance remains yours.').supplemental=true;
if(lesson.id==='missions'&&step===14)shot('Find the\nledger and feed','The mission dashboard has its ledger and live Worker feed beside the task graph. Inspect recorded events and evidence when you need to understand progress.',{screen:'mission-graph',crop:[1040,720,535,260],highlight:[1050,789,516,187],callout:'Ledger · live Worker feed'},'This clean fixture has no events or active Worker. Read the real entries in your own mission.').supplemental=true;
if(lesson.id==='modes-controls'&&[8,9].includes(step))shot(step===8?'Modern\nPause control':'Modern\nResume control',step===8?'Modern shows Pause in the footer while work is running. Read the confirmed paused state after using it.':'The footer shows Resume for paused work. Correct the goal first, then continue deliberately.',{screen:'@video5/'+(step===8?'modern-working':'modern-paused'),crop:[1275,936,135,64],highlight:step===8?[1315,959.5,28,17]:[1305,959.5,38,17],callout:step===8?'Pause running companion work':'Resume paused companion work'},'Demonstration state. Check the resulting state in your own session.').supplemental=true;
if(lesson.id==='missions'&&step===13)shot('Pause or\nAbort the mission','Mission Pause is on the left. Abort is on the right. Read the confirmed mission status after using its own control.',{screen:'mission-recovery',crop:[510,75,550,65],highlight:[519,87,532,30],callout:'Mission Pause · mission Abort'},'A stopped companion and an aborted mission are different states.').supplemental=true;
if(lesson.id==='mission-options'&&step===2)shot('A separate\nexecution floor','The Worker execution floor sets the minimum step budget when a leaf runs. Read it separately from the largest assignment size.',{screen:'missions-settings',crop:[690,930,340,48],highlight:[754,945,260,31],callout:'Minimum step budget'},'Planner estimates remain visible. A budget is not a promise of successful completion.').supplemental=true;
if(s.tip)list('A useful\ndetail',chunks(s.tip,22),lesson.id==='missions'&&step===7?'In the website course this is interactive. The next card explains the same dependency example here.':'Keep this distinction in mind as you practice.',24);
const p=practice[lesson.id][step-1];list(p[0],p[1],p[2],28);const check=list('Pause and\ncheck this',[s.checkpoint],'Try it in Genesis. Pause for as long as you need. Continue when you can explain or confirm this result.',22);check.checkpointSteps=[step];check.sourceSteps=[];
}step=null;list('Lesson\ncomplete',['Read the actual state before continuing','Check the files, facts and required resources','Use the controls for the process you intend','Inspect the result before accepting it'],'Return to any step using its lesson chapter. Clear instructions and actual evidence make the result easier to judge.',24);}
chapter=6;lesson=null;step=null;list('Your finished\nwork checklist',['A plan tracks work; inspect the actual output','Choose the mode and Work policy deliberately','Schedules need available time and resources','Missions use checked dependencies and recovery','The owner keeps final acceptance and authority'],'All six lessons and all 45 steps of “Turn ideas into finished work” are now covered.',31);
add('title','Ready to\nconnect more.',{body:'Practice on one small job you can inspect.\nNext in video 6: Open up the possibilities — the entire next category.',tag:'PAUSE · PRACTICE · RETURN'},20);
for(const s of scenes){s.title=s.title.trimEnd();const words=[s.title,s.body,s.note,s.quote,...(s.items||[]),...(s.cards||[]).flatMap(c=>[c.title,c.body,c.tag])].filter(Boolean).join(' ').split(/\s+/).length;s.readingWords=words;s.readingSeconds=words/150*60;s.locateSeconds=s.kind==='screen'?7:4;s.duration=Math.max(s.duration,Math.ceil(s.readingSeconds+s.locateSeconds+3));}
const data={title:'Turn ideas into finished work',subtitle:'Complete category 4',music:'C:/Development-Gen/songs/video 5 song.mp3',outputFolder:'output/video-05',filename:'Genesis-Turn-Ideas-Into-Finished-Work.mp4',lessonIds:ids,chapters:['Introduction',...lessons.map(l=>l.title)],progressLabels:labels,sourceLessons:lessons,audio:{repeatStart:8,trimEnd:237,crossfade:8,fadeIn:4,fadeOut:8,rationale:'The decoded track is 239.6535 s. Its opening through 7 s is quieter; repeat from 8 s after that introduction. End each copy at 237 s before the measured terminal collapse (-39.8 dB RMS at 238.5 s and -52.8 at 239 s). Equal-power 8 s overlaps maintain the bed; retain the opening once and fade only at the video ends.'},scenes};
fs.writeFileSync(path.join(root,'timeline-video5.json'),JSON.stringify(data,null,2));console.log(JSON.stringify({scenes:scenes.length,total:scenes.reduce((n,s)=>n+s.duration,0),steps:lessons.reduce((n,l)=>n+l.steps.length,0)}));
