/* Entire category 5: exact course teaching, with current controls and safe examples. */
const fs=require('fs'),path=require('path');const root=__dirname;
const catalog=JSON.parse(fs.readFileSync(path.resolve(root,'../tutorials/assets/scenes.json'))),ids=['browser','computer','plugins','code','github','phone-telegram','approvals','pets','file-boundaries'],lessons=ids.map(id=>catalog.lessons.find(l=>l.id===id));
if(JSON.stringify(catalog.lessons.filter(l=>l.group==='connect').sort((a,b)=>a.coursePosition-b.coursePosition).map(l=>l.id))!==JSON.stringify(ids))throw Error('Category order changed');
const labels=['BROWSER','CONTROL','PLUGINS','CODE','GITHUB','PHONE','APPROVALS','PETS','FILES'],scenes=[];let chapter=0,lesson=null,step=null;
function add(kind,title,fields={},duration=24){const s={chapter,lesson:lesson?.id||null,sourceSteps:step?[step]:[],duration,kind,eyebrow:chapter?`${String(chapter).padStart(2,'0')} / ${labels[chapter-1]}${step?' · STEP '+step:''}`:'GENESIS AI · CATEGORY 5',title,...fields};scenes.push(s);return s}
function list(title,items,note='',duration=26){return add('list',title,{items,note},duration)}
function shot(title,body,g,note=''){return add('screen',title,{body,...g,note,contextZoom:false},26)}
const old=fs.readFileSync(path.join(root,'build-video5.cjs'),'utf8');eval(old.slice(old.indexOf("const {createCanvas"),old.indexOf('const titles=' )).replace('function chunks','globalThis.chunks=function chunks'));
const titles={browser:['Choose your\nbrowser route','Connect the\nexact browser','Read the\nconnection state','Try a\npublic page','Return control\ndeliberately','Watch while\nyou learn'],computer:['Four separate\ncontrol categories','Allow the\nneeded access','Handoff before\nyou type','Check each\naccess layer'],plugins:['Find an\nindividual action','Review, then\nenable a plugin','Connect the\nneeded service','An outside\ntool server','Advanced\nlifecycle hooks','Quick page\nor Manage?'],code:['Choose your\ncode folder','A local\nundo history','Inspect before\ngoing back','A separate\nexperiment folder','Review, test,\nthen bring back','Local saving\nand publication'],github:['Your private\nGitHub token','Choose the\nlocal destination','Save a\nclear change','Three distinct\noutward actions','Get updates\nand verify'], 'phone-telegram':['The computer\nis the engine','Pair your\nAndroid device','Connect your\nTelegram bot','Restrict the\nintended chat','Choose the\nactivity level','Answer a\nrequest once'],approvals:['Read exactly\nwhat is proposed','The sign-in\nyou expected','Decline or\nexplain a change','Inspect the\nfinal result'],pets:['Choose your\ndesktop companion','Quick access\nto the same app','Show, hide\nand focus'], 'file-boundaries':['Find the\nworking folder','Allow a\nspecific folder','Understand the\nprotection boundary','Time for a\nknown command']};
let extra;function actual(name,match,{crop,highlight,callout}={}){extra ||= JSON.parse(fs.readFileSync(path.join(root,'assets/video6/screens.json')));const img=extra.screens[name];if(!img)throw Error('Missing current capture '+name);const controls=img.controls||[];const found=controls.filter(c=>new RegExp(match,'i').test([c.text,c.label,c.aria].filter(Boolean).join(' ')));let a=found.find(c=>c.text===match||c.label===match)||found[0];if(!highlight&&a){highlight=[a.x-a.w/2,a.y-a.h/2,a.w,a.h]}
if(!highlight)throw Error('No anchor '+name+' '+match+' '+JSON.stringify(controls.slice(0,3)));if(!crop){const [x,y,w,h]=highlight;const cw=Math.min(img.width,Math.max(470,w+80)),ch=Math.min(img.height,Math.max(135,h+100));crop=[Math.max(0,Math.min(img.width-cw,x-40)),Math.max(0,Math.min(img.height-ch,y-50)),cw,ch]}
return {screen:'@video6/'+name,crop,highlight,callout:callout||match}}
function geometry(s){let screen=path.basename(s.screenshot,'.png'),a=s.anchor,highlight=[a.x-a.width/2,a.y-a.height/2,a.width,a.height],callout=a.label,crop;
if(lesson.id==='browser'&&[2,3].includes(step))return actual('computer-states','Your browsers',{crop:[265,440,765,255],highlight:[280,465,735,215],callout:'Per-browser setup and connection state'});
if(lesson.id==='browser'&&step===5)return actual('browser-handoff','Resume AI',{callout:'Resume AI returns browser control'});
if(lesson.id==='computer'&&[1,2,4].includes(step))return actual('computer-states','Any app',{crop:[270,335,765,470],highlight:step===2?[280,460,735,220]:[280,345,735,440],callout:'Read each category label and its own permission'});
if(lesson.id==='computer'&&step===3)return actual('desktop-handoff','Resume AI',{callout:'Resume AI returns desktop control'});
if(lesson.id==='plugins'&&step===1)return actual('plugins-skills','Enable tool read_file',{crop:[275,275,760,290],highlight:[305,430,330,35],callout:'Read file action and its individual switch'});
if(lesson.id==='plugins'&&step===2)return actual('plugins-import','Import a plugin',{callout:'Add → Import a plugin'});
if(lesson.id==='code'){const names=['code-folder','code-history','code-history','code-copy','code-copy','code-history'],matches=['garden-page','Take a snapshot now','Go back here','Make a safe copy','Bring back','Save'];return actual(names[step-1],matches[step-1],{callout:matches[step-1]});}
if(lesson.id==='github'){const names=['github-disconnected','github-connected','code-history','github-connected','github-connected'],matches=['Paste your token','Download','See changes','Upload','Get updates'];return actual(names[step-1],matches[step-1],{callout:matches[step-1]});}
if(lesson.id==='pets'&&step===1)return actual('pets-top','Show mini',{callout:'Show mini · Show pet on desktop'});
if(lesson.id==='pets'&&step===2)return {screen:'@video6/mini',crop:[0,0,166,210],highlight:[17,169,132,33],callout:'Chat · voice · menu'};
if(lesson.id==='pets'&&step===3)return actual('pets-top','Show mini',{callout:'Show / Hide mini'});
const w=Math.min(1500,Math.max(470,highlight[2]+80)),h=Math.min(450,Math.max(135,highlight[3]+100));crop=[Math.max(0,Math.min(1600-w,highlight[0]-40)),Math.max(0,Math.min(1000-h,highlight[1]-50)),w,h];return {screen,crop,highlight,callout}}
const examples={
browser:[
['One browser\nfor your task',['Genesis browser has its own profile','Browser Bridge uses your personal browser','Choose the route where the needed page is available','Check which sign-in belongs to that route'],'Example: a public page can be read in Genesis. Your existing personal login belongs to its own browser profile.'],
['Chrome and\nEdge are separate',['Find the browser you intend to use','Use that browser’s Set up flow if needed','Check the extension in that same browser','Read its own connected or paired state'],'Setting up Chrome does not connect Edge. Never share private pairing information in a screenshot.'],
['Three useful\nconnection states',['Connected: the extension is answering','Set up but closed: open that browser','Not set up: follow its extension setup','Open but silent: inspect connection and retry state'],'A paired closed browser is different from a missing extension. Read the exact name before changing anything.'],
['Read a\nharmless page',['Ask: “Open this public page.”','Ask for its three main points','Watch using View → Browser','Compare the summary with the visible page'],'Begin with material you may read without signing in. A successful connection cannot remove website access restrictions.'],
['Handoff\nstep by step',['Pause AI keeps Genesis out of the browser','Complete the expected site step yourself','Resume AI returns ordinary browser control','For a requested challenge, use Done after finishing'],'Current labels: Pause AI, Resume AI and Done. Read the resulting state; a finished reply may need a new request to continue.'],
['Keep the\npage visible',['Choose visible browsing while learning','Headless hides the browser window','Page-settle time allows loading to finish','Navigation gaps space repeated visits'],'Change an advanced timing value only for a known need. Check the page and result after trying again.']
],
computer:[
['Access for\none useful job',['Any app: screen, mouse and keyboard','Genesis browser: its own web workspace','Your browsers: Browser Bridge entries','Documents: supported document operations'],'More apps covers connected MCP services. Each category has its own permission; one switch does not grant the others.'],
['A small\npermission decision',['Name the task and intended surface','Enable its specific category','Check its per-browser or per-server entry','Confirm the connection as well as permission'],'Example: reading one personal-browser page needs its route and connection. A document-only task does not need all desktop access.'],
['Avoid competing\ninput',['Read the desktop control bar','Choose Take control before you type','Complete your own interaction','Choose Resume AI when you are ready'],'The bar can finish an input event already underway before handing over. Inspect the confirmed state.'],
['Check the\nmissing layer',['Is the individual action enabled?','Is the computer category permitted?','Is the browser or server connected?','Does the intended service have its credential?'],'A failed action is a reason to inspect its layers. Enabling everything may still leave its actual connection missing.']
],
plugins:[
['Find one\nfile action',['Open Settings → Plugins → Skills','Search for read_file','Read its description before using it','Check the individual action switch'],'A skill can explain how to use tools. The action switch and service connection still have separate roles.'],
['Review a\nknown package',['Add → Import a plugin selects a local folder','Read what that package can do','Trust the specific reviewed version','Enable only after that review'],'The tutorial does not install a package. Importing is a review step; enabling authorises its supported capabilities.'],
['A service\nconnection example',['Choose the service your task needs','Read its card’s supported capabilities','Enter the key in its own private field','Check the configured connection state'],'A service key does not promise every feature of a signed-in website account. Keep real keys out of shared examples.'],
['Follow the\nserver’s instructions',['Local stdio uses a documented command','Streamable HTTP uses a documented URL','Legacy SSE is a separate transport','Check connection and each exposed tool'],'Use a trusted server and supported transport. A connected server can still have individual actions disabled.'],
['An advanced\nevent command',['A lifecycle event triggers the hook','A reviewed command handles that event','Its supported contract defines the effect','Enable only the reviewed version you trust'],'Example: a before-tool command may deny an action. Hooks are optional; ordinary chatting does not require one.'],
['Choose the\nright doorway',['Left-panel Plugins is quick browsing','Manage opens the fuller Settings hub','Use Settings for keys and server editing','Read the exact integration capability'],'A model endpoint connects a model service. It does not automatically connect account apps or every connector.']
],
code:[
['A disposable\npractice project',['Use a small code folder you own','Add it under Code → Overview','Confirm the complete folder path','Check whether Git is ready'],'The captured garden-page is a labelled example. Optional private Git setup needs consent; no owner code is changed here.'],
['Keep a\nstarting point',['Select the intended folder in History','Use Take a snapshot now before an experiment','Read the snapshot’s label and time','Check the folder each snapshot belongs to'],'A code snapshot records that folder’s version. Use Genesis backup for memories and other app data.'],
['Inspect the\nversion first',['Read Changes for the saved point','Confirm folder, label and date','Use Go back here deliberately','History keeps a Before going back snapshot'],'A return has an undo point. Read the actual files afterward; unrelated data is outside the code history promise.'],
['A button-size\nexperiment',['Name the experiment “Larger button”','Make a safe copy','Give Genesis the copy’s complete path','Leave the original available for comparison'],'The copy is a separate folder on its own branch, starting with current files and unsaved changes.'],
['Before\nBring back',['Inspect the copy’s Changes','Run the project’s relevant checks','Read Code review findings as suggestions','Check any clash before choosing a version'],'A review is not proof the program works. Bring back snapshots the original; a clash needs a deliberate choice.'],
['Two separate\ndecisions',['Snapshot or Save records local code','Bring back changes the local original','GitHub upload makes an outward change','Choose publication separately when intended'],'Keeping a local version does not create an online repository or submit a pull request.']
],
github:[
['Connect your\nintended account',['Use a token with appropriate repository access','Keep the token private','Enter it in Code → GitHub','Confirm the displayed account after connecting'],'The connection views here are labelled demonstration states. No real token is entered and no account connection is made.'],
['Choose where\nthe project goes',['Select the intended repository','Confirm its local download destination','Or add your existing folder under Code','Read the local path before editing'],'A repository is a project plus version history. Two similarly named folders can still be different destinations.'],
['A useful\nsave message',['Inspect the changed files','Example: “Increase garden button padding”','Save the intended local version','Know which committed change you will upload'],'A commit is a labelled local saved version. Unsaved edits and uploaded commits are different states.'],
['Publication\nchoices',['Put on GitHub: create an online repository','Upload: send commits to the configured remote','Open pull request: propose changes for review','Check destination, name, privacy and result'],'These actions have different effects. No outward action is run in this tutorial.'],
['Inspect both\ncopies',['Get updates brings remote changes locally','Read conflicts when both versions changed','Open the actual repository or pull request','Check files, destination and visible result'],'Posting a review shares it with people who can see that pull request. A local review alone does not post it.']
],
'phone-telegram':[
['A remote\ndoorway',['The desktop runs Genesis and its model','Its memory stays with that desktop','Keep Genesis running and reachable','Choose Android or Telegram setup separately'],'A connected phone does not move the whole AI onto the handset. Check the computer before diagnosing a remote failure.'],
['Pair the\nintended device',['Open Pair Mobile Device','Follow the private displayed pairing flow','Complete that flow in the Android app','Confirm the device before controlling work'],'You can also reach pairing through Finish setting up. Pairing details should not be shown in a shared tutorial or message.'],
['Your own\nbot setup',['Get a bot token from BotFather','Enter Bot token in Communications','Enable the bridge and save','Press Start in your bot and read its status'],'Use only your intended bot and keep its real token private. This video does not configure a messaging account.'],
['An explicit\nallowed chat',['Message your own intended bot','Check the observed chat in Allowed users','Use Allow only… for that chat','Verify the resulting restriction'],'An empty list uses the first chat that messages it. An explicit intended-chat restriction is clearer for unattended use.'],
['How much\nactivity to send',['Silent: fewer activity messages','Status: one edited live activity card','Verbose: more individual steps','Use alert controls or /unplug as needed'],'Mute sounds and pausing alerts differ from disconnecting the bridge. Enable it again from Genesis when you intend.'],
['One valid\nanswer wins',['Read which request reached each surface','Answer it on one intended surface','The first valid answer resolves it','Check the resulting state before replying again'],'Email-code reading and SMS forwarding have separate permissions. Start with manual answers to expected requests.']
],
approvals:[
['Read before\nyou decide',['What exact action is proposed?','Which destination will it affect?','What result is expected?','Ask for clarification if this is unclear'],'A request for help is specific. Do not infer permission for a different destination or a broader action.'],
['An expected\nverification step',['Check the intended site and account','Use the offered owner handoff','Complete the required site check yourself','Return control after checking the result'],'Genesis does not solve a CAPTCHA for you. An unexpected code can belong to a different sign-in.'],
['Say what\nyou mean',['Decline an action you do not want','Explain the changed destination or result','Answer missing facts when that is the need','Read the specific updated request'],'Example: “Draft this message, but do not send it.” One approval does not approve every later action.'],
['Accept the\nactual work',['Open the project’s file from Review','Compare it with your requested result','For a mission, read owner sign-off conditions','Describe any missing part before accepting'],'A model’s finished message and your acceptance are separate. Inspect the real delivery and its source material.']
],
pets:[
['The current\npet collection',['Genesis AI Earth','Terminator - Calm / Terminator 1 - Active','Conversation Orb - Calm','Conversation Orb - Active'],'These are the five pets in this version of Genesis. Choose the one you like; the available collection can vary by version.'],
['The same\nGenesis doorway',['Drag the top handle to move the mini','Chat opens your Genesis conversation','Voice opens its voice controls','Menu offers pets, Settings and Hide mini'],'The mini uses the same app, model and memory. It is a convenient doorway, not a new conversation engine.'],
['Show or hide\nwhen useful',['Use Show mini or Hide mini in Settings','Show pet on desktop controls the preference','Alt + Win + P can show and focus it','If the shortcut is busy, use Show mini'],'The selected pet can return at Genesis startup. Hiding it does not erase the conversation.']
],
'file-boundaries':[
['Ordinary output\nor code folder?',['Read Workspace under System → Tool access','Use that folder for ordinary outputs','Code selects a versioned project folder','Specify the path when a different folder is needed'],'The normal workspace follows the installation. Adding a Git folder under Code is a separate operation.'],
['A specific\nwrite destination',['Add the exact project folder path','Use one allowed folder per line','Save the intended path list','Check the resulting file location'],'Example: allow a disposable practice folder. Do not add every drive simply to bypass a failed write.'],
['A supported\ntool boundary',['Protected files restrict supported tool writes','Core read-only protects core identity paths','Read which path the setting covers','A shell or outside program has its own effects'],'These controls are not an operating-system sandbox for every command. Keep important data protected through the appropriate boundary.'],
['A known\nlonger build',['Read the actual command and result','Increase Bash timeout for a known slow job','Save the change and inspect the next run','Separate timeout from provider failure'],'More time cannot repair a wrong command, a missing file or a disconnected model. Diagnose the actual error.']
]};
add('title','Open up the\npossibilities.',{body:'Browsers, useful tools, code and your phone.\nNine complete lessons, with the choices and boundaries you keep.',tag:'VIDEO 6 · COMPLETE CATEGORY 5'},18);
for(let start=0;start<9;start+=3)list(start===0?'Connect useful\ncapabilities':start===3?'Code and\nremote access':'Choices you\nkeep',lessons.slice(start,start+3).map(l=>l.title),'Have Genesis open. Pause to practice. Captures use clean demonstration states; examples are not live model results.',26);
for(let n=0;n<9;n++){chapter=n+1;lesson=lessons[n];step=null;add('title',['A browser\nyou can observe.','Choose the\nright access.','Useful tools.\nDeliberate setup.','An experiment\nyou can undo.','Local work.\nShared deliberately.','Your desktop,\nwithin reach.','Read. Decide.\nCheck the result.','A companion\nwithin reach.','The right folder.\nThe right boundary.'][n],{body:lesson.title+'\n'+['Profiles, extension status and owner handoff.','Permissions, tools, credentials and connections.','Skills, plugins, Apps, MCP and Hooks.','History, safe copies, changes and your testing.','Token privacy, destinations and outward actions.','Android pairing and a separate Telegram bridge.','Specific approvals and your final acceptance.','The current Genesis pets and their little controls.','Workspace, allowed writes, protection and timeouts.'][n],tag:`LESSON ${n+1} OF 9`},18);
list('Before\nyou begin',chunks(lesson.prerequisites,18),'Prepare these prerequisites before trying the lesson. Pause whenever you need time in Genesis.',24);
for(const s of lesson.steps){step=s.step;const blocks=chunks(s.narrationDraft),g=geometry(s);for(let j=0;j<blocks.length;j++)shot(titles[lesson.id][step-1],blocks[j],g,`Step ${step} of ${lesson.steps.length}${blocks.length>1?' · Teaching '+(j+1)+' of '+blocks.length:''}. ${j===0?'Locate the highlighted control.':'Read this distinction before acting.'}`);
if(s.tip)list('A useful\ndetail',chunks(s.tip,22),'Keep this distinction in mind as you practice.',24);
const p=examples[lesson.id][step-1];list(p[0],p[1],p[2],28);
if(lesson.id==='browser'&&step===4)shot('Watch the\nintegrated browser','The current workspace shows tabs, an address and page controls beside Genesis. Start with a harmless public page and compare the summary with the page.',actual('browser-active','Browser address',{crop:[0,30,1600,650],highlight:[12,72,1576,61],callout:'Tabs · address · page controls'}),'A clean local demonstration state. This capture does not prove access to a signed-in website.').supplemental=true;
if(lesson.id==='browser'&&step===5)shot('Read the\ncurrent label','In this version, Pause AI performs ordinary browser handoff. Resume AI returns control. When Genesis requests a site step, Done confirms that you completed it.',actual('browser-active','Pause AI',{callout:'Pause AI: hand the browser to yourself'}),'Browser handoff is separate from mission Resume and from starting another model turn.').supplemental=true;
if(lesson.id==='browser'&&step===5)shot('A requested\nsite step','When Genesis asks you to complete a site check, read its reason. Complete the expected step yourself and use Done only afterward.',actual('browser-request','Done',{callout:'Done: confirm the requested site step'}),'This fixture has no live sign-in or CAPTCHA. The request belongs to the intended browser surface.').supplemental=true;
if(lesson.id==='computer'&&step===3)shot('Find Take\ncontrol','Read the blue desktop control bar. Take control stops further desktop actions while you act. Resume AI returns that surface when you are ready.',actual('desktop-active','Take control',{callout:'Take control on the desktop bar'}),'Only a labelled demonstration state is shown. No live desktop task competes with owner input.').supplemental=true;
if(lesson.id==='code'&&step===3)shot('Read the\nchanged lines','Changes shows files and their additions and removals. In this example, button padding changes from 8 to 14 pixels. Inspect the intended version before restoring.',actual('code-changes','Practice changes',{crop:[270,795,765,185],highlight:[280,810,735,150],callout:'Files and changed lines'}),'Illustrative disposable-project changes, rendered by the current Code interface. No owner file was restored.').supplemental=true;
if(lesson.id==='plugins'&&step===6)shot('The quick\nPlugins page','The left-panel page lets you browse capabilities quickly. Use Manage for the full Settings controls when you need keys, imports or server editing.',actual('plugins-quick','Manage',{callout:'Manage opens Settings'}),'A clean fixture. No package is installed, no server is connected and no key is entered.').supplemental=true;
if(lesson.id==='pets'&&step===1)shot('Read the current\ncollection','The current Settings list and mini menu offer five pets. Choose a style you like; all of them open the same Genesis app.',actual('pets-list','Conversation Orb - Active',{crop:[265,300,765,665],highlight:[285,750,357,205],callout:'Current Genesis pet collection'}),'The two Terminator styles and two Conversation Orb styles are separate choices, alongside Genesis AI Earth.').supplemental=true;
if(lesson.id==='pets'&&step===3)shot('Hide the\nmini','When the mini is enabled, the same Settings control reads Hide mini. Use it when you want the desktop clear, then Show mini when useful again.',actual('pets-enabled','Hide mini',{callout:'Hide mini keeps your conversation'}),'The startup preference and shortcut availability belong to this computer.').supplemental=true;
const check=list('Pause and\ncheck this',[s.checkpoint],'Try it in Genesis. Pause for as long as you need. Continue when you can explain or confirm this result.',22);check.checkpointSteps=[step];check.sourceSteps=[];
}step=null;list('Lesson\ncomplete',['Read the actual state before continuing','Check the intended surface and destination','Keep credentials and pairing details private','Inspect the result of the action you chose'],'Return to any step using the lesson chapter. Practice on material and folders you own.',24);}
chapter=9;lesson=null;step=null;list('Your connection\nchecklist',['Choose the correct browser or control surface','Check tools, permissions and connections separately','Try code changes in a disposable safe copy','Approve specific actions and inspect real results','Use the exact working folder the task needs'],'All nine lessons and all 44 steps of “Open up the possibilities” are covered.',31);
add('title','Keep Genesis\nyours.',{body:'Practice one useful connection at a time.\nNext in video 7: the complete Memory & Care category.',tag:'PAUSE · PRACTICE · RETURN'},20);
for(const s of scenes){s.title=s.title.trimEnd();const words=[s.title,s.body,s.note,s.quote,...(s.items||[]),...(s.cards||[]).flatMap(c=>[c.title,c.body,c.tag])].filter(Boolean).join(' ').split(/\s+/).length;s.readingWords=words;s.readingSeconds=words/150*60;s.locateSeconds=s.kind==='screen'?7:4;s.duration=Math.max(s.duration,Math.ceil(s.readingSeconds+s.locateSeconds+3))}
const audio={repeatStart:.5,trimEnd:105.5,crossfade:4,fadeIn:3,fadeOut:7,rationale:'Decoded length 106.4135 s. Opening begins with music (-16.7 dB RMS in first half-second); from 0.5 s it is established near -13 dB. Ending remains musical through 105.5 s, then drops to -39.3 dB RMS at 106 s. Repeat 0.5–105.5 s, keeping the opening once, with equal-power 4 s overlaps over the late recovery (101.5–105.5 s). Retain the musical breakdown at 98.5–103 s; it is low-level music, not silence. Use 3 s opening / 7 s closing fades only at the video ends.'};
const data={title:'Open up the possibilities',subtitle:'Complete category 5',music:'C:/Development-Gen/songs/Video 6 song.mp3',outputFolder:'output/video-06',filename:'Genesis-Open-Up-The-Possibilities.mp4',lessonIds:ids,chapters:['Introduction',...lessons.map(l=>l.title)],progressLabels:labels,sourceLessons:lessons,audio,scenes};fs.writeFileSync(path.join(root,'timeline-video6.json'),JSON.stringify(data,null,2));console.log(JSON.stringify({scenes:scenes.length,total:scenes.reduce((n,s)=>n+s.duration,0),steps:44}));
