const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {createCanvas,loadImage}=require('C:/Users/damir/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const root=__dirname,out=path.join(root,'output/video-06'),evidence=path.resolve(root,'../../../Claude and OpenAI docs/Genesis-Knowledge/evidence/tutorial-video-6-20261003');fs.mkdirSync(evidence,{recursive:true});
async function main(){const data=JSON.parse(fs.readFileSync(path.join(root,'timeline-video6.json')));const manifest={date:'2026-10-03',scenes:data.scenes.length,total:data.scenes.reduce((a,s)=>a+s.duration,0),lessons:[],files:{}};
for(const l of data.sourceLessons){const mapping=l.steps.map(s=>({step:s.step,title:s.title,teachingBeats:data.scenes.map((b,i)=>b.lesson===l.id&&b.sourceSteps.includes(s.step)?i+1:null).filter(Boolean),checkpointBeats:data.scenes.map((b,i)=>b.lesson===l.id&&b.checkpointSteps?.includes(s.step)?i+1:null).filter(Boolean)}));if(mapping.some(m=>!m.teachingBeats.length||!m.checkpointBeats.length))throw Error('Missing teaching or checkpoint');manifest.lessons.push({id:l.id,prerequisites:l.prerequisites,steps:mapping});}
for(const name of ['render.cjs','timeline.json','review.html','verify.cjs','output/Genesis-Your-First-Five-Minutes.mp4'])manifest.files[name]=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,name))).digest('hex');
manifest.songSha256=crypto.createHash('sha256').update(fs.readFileSync(data.music)).digest('hex');
manifest.preservationBaseline='preservation-baseline.json';
const norm=t=>t.replace(/\s+/g,' ').trim();manifest.exactSourceText=[];
for(const l of data.sourceLessons){const prereq=data.scenes.find(b=>b.lesson===l.id&&b.title==='Before\nyou begin');if(norm(prereq.items.join(' '))!==norm(l.prerequisites))throw Error('Prerequisite text missing: '+l.id);
 for(const s of l.steps){const beats=data.scenes.filter(b=>b.lesson===l.id&&b.sourceSteps.includes(s.step));const teaching=norm(beats.filter(b=>b.kind==='screen'&&!b.supplemental).map(b=>b.body).join(' '));const tip=norm(beats.filter(b=>b.title==='A useful\ndetail').flatMap(b=>b.items).join(' '));if(teaching!==norm(s.narrationDraft)||tip!==norm(s.tip))throw Error('Source words omitted: '+l.id+'/'+s.step);const check=data.scenes.find(b=>b.lesson===l.id&&b.checkpointSteps?.includes(s.step));if(!check.items.includes(s.checkpoint))throw Error('Checkpoint missing');manifest.exactSourceText.push({lesson:l.id,step:s.step,teaching:true,tip:true,checkpoint:true});}}
const baseline=JSON.parse(fs.readFileSync(path.join(evidence,'preservation-baseline.json')));if(baseline.files.some(p=>crypto.createHash('sha256').update(fs.readFileSync(p.file)).digest('hex')!==p.sha256))throw Error('An earlier source or output changed');manifest.preservedFiles=baseline.files.length;
fs.writeFileSync(path.join(evidence,'preflight.json'),JSON.stringify(manifest,null,2));fs.writeFileSync(path.join(out,'step-coverage.json'),JSON.stringify(manifest.lessons,null,2));
for(let start=0;start<data.scenes.length;start+=6){const canvas=createCanvas(1920,1680),c=canvas.getContext('2d');c.fillStyle='#0c0e16';c.fillRect(0,0,1920,1680);for(let j=0;j<6&&start+j<data.scenes.length;j++){let img=await loadImage(path.join(out,`scene-${String(start+j+1).padStart(2,'0')}.png`));c.drawImage(img,j%2*960,Math.floor(j/2)*560,960,540);c.fillStyle='#e8bf72';c.font='16px Segoe UI';c.fillText('Beat '+(start+j+1),j%2*960+12,Math.floor(j/2)*560+554)}fs.writeFileSync(path.join(evidence,`storyboard-${String(start/6+1).padStart(2,'0')}.jpg`),canvas.toBuffer('image/jpeg',90));}
console.log(JSON.stringify({evidence,...manifest,files:'Pilot hashes recorded'}));}
main().catch(e=>{console.error(e);process.exit(1)});
