/* Editable 1080p/30fps Genesis tutorial renderer. Original screenshots are read only. */
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),{once}=require('node:events');
const packageRoot=process.env.CODEX_NODE_PACKAGES||'C:/Users/damir/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {createCanvas,loadImage,GlobalFonts}=require(path.join(packageRoot,'@napi-rs/canvas'));
GlobalFonts.registerFromPath('C:/Windows/Fonts/segoeui.ttf','Genesis');
GlobalFonts.registerFromPath('C:/Windows/Fonts/segoeuib.ttf','Genesis Bold');
GlobalFonts.registerFromPath('C:/Windows/Fonts/segoeuil.ttf','Genesis Light');
const root=__dirname,assets=path.resolve(root,'../tutorials/assets');
const data=JSON.parse(fs.readFileSync(path.join(root,'timeline-video7.json'),'utf8'));
const output=path.join(root,data.outputFolder);fs.mkdirSync(output,{recursive:true});
const ffmpeg=process.env.FFMPEG_PATH||fs.readdirSync(path.join(root,'vendor/imageio_ffmpeg/binaries')).filter(n=>n.endsWith('.exe')).map(n=>path.join(root,'vendor/imageio_ffmpeg/binaries',n))[0];
const W=1920,H=1080,FPS=30,total=data.scenes.reduce((n,s)=>n+s.duration,0);
const C={bg:'#0c0e16',panel:'#171b27',gold:'#e8bf72',text:'#f4f1eb',muted:'#aeb6ca',purple:'#9c7eff',border:'#333a4b'};
const canvas=createCanvas(W,H),ctx=canvas.getContext('2d');let logo;const images={};
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),ease=x=>1-Math.pow(1-clamp(x),3);
function rounded(c,x,y,w,h,r,fill,stroke){c.beginPath();c.roundRect(x,y,w,h,r);if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=2;c.stroke()}}
function txt(c,text,x,y,size=40,color=C.text,font='Genesis',max){c.fillStyle=color;c.font=`${size}px "${font}"`;c.textBaseline='top';if(max)c.fillText(text,x,y,max);else c.fillText(text,x,y)}
function wrap(c,text,x,y,width,size=40,color=C.text,font='Genesis',line=1.37){c.font=`${size}px "${font}"`;let lines=[];for(const paragraph of text.split('\n')){let row='';for(const word of paragraph.split(' ')){const next=row?row+' '+word:word;if(c.measureText(next).width>width&&row){lines.push(row);row=word}else row=next}lines.push(row)}for(const [i,l]of lines.entries())txt(c,l,x,y+i*size*line,size,color,font);return y+lines.length*size*line}
function layer(draw){const a=createCanvas(W,H),c=a.getContext('2d');draw(c);return a}
function label(c,text,x,y){txt(c,text,x,y,23,C.gold,'Genesis Bold')}
function screenLayer(s,override){return layer(c=>{const box={x:880,y:246,w:944,h:658},crop=override||s.crop;rounded(c,box.x-8,box.y-8,box.w+16,box.h+16,25,'#080a11',C.border);c.save();c.beginPath();c.roundRect(box.x,box.y,box.w,box.h,20);c.clip();c.fillStyle='#121621';c.fillRect(box.x,box.y,box.w,box.h);const scale=Math.min(box.w/crop[2],box.h/crop[3]),dw=crop[2]*scale,dh=crop[3]*scale,dx=box.x+(box.w-dw)/2,dy=box.y+(box.h-dh)/2;c.drawImage(images[s.screen],...crop,dx,dy,dw,dh);c.restore();if(s.highlight){const h=s.highlight,hx=dx+(h[0]-crop[0])*scale,hy=dy+(h[1]-crop[1])*scale,hw=h[2]*scale,hh=h[3]*scale;c.strokeStyle='#f2c56a';c.lineWidth=4;c.beginPath();c.roundRect(hx-5,hy-5,hw+10,hh+10,8);c.stroke();const ex=clamp(hx+hw/2,box.x+60,box.x+box.w-60),ey=hy+hh+6,ly=956;c.beginPath();c.moveTo(ex,ey);c.lineTo(ex,928);c.lineTo(box.x+60,928);c.lineTo(box.x+60,ly-8);c.strokeStyle=C.gold;c.lineWidth=2;c.stroke();label(c,s.callout,box.x+60,ly)}label(c,'GENESIS INTERFACE',box.x,205);});}
function listRows(c,text){c.font='33px Genesis';const rows=[];let row='';for(const word of text.split(' ')){const next=row?row+' '+word:word;if(c.measureText(next).width>810&&row){rows.push(row);row=word}else row=next}rows.push(row);return rows;}
function makeLayers(s){const heading=layer(c=>{label(c,s.eyebrow,96,199);if(s.kind==='title')return;wrap(c,s.title,96,254,700,62,C.text,'Genesis Light',1.13)});const body=layer(c=>{
 if(s.kind==='screen'){wrap(c,s.body,100,436,678,40);rounded(c,96,746,696,193,18,C.panel);wrap(c,s.note,122,773,646,30,C.muted);}
 if(s.kind==='list'){let y=340;for(let i=0;i<s.items.length;i++){rounded(c,865,y,952,100,16,C.panel,C.border);txt(c,String(i+1).padStart(2,'0'),895,y+28,30,C.gold,'Genesis Bold');const rows=listRows(c,s.items[i]);rows.forEach((row,j)=>txt(c,row,970,y+(100-(rows.length-1)*39.6-40)/2+j*39.6,33,C.text,'Genesis'));y+=118;}wrap(c,s.note,100,535,654,34,C.muted);}
 if(s.kind==='compare'){let x=96;for(const card of s.cards){rounded(c,x,418,835,467,24,C.panel,C.border);label(c,card.title,x+35,451);wrap(c,card.body,x+35,511,765,36);txt(c,card.tag,x+35,824,27,C.gold);x+=885;}wrap(c,s.note,100,939,1665,29,C.muted);}
 if(s.kind==='quote'){rounded(c,852,294,966,454,26,C.panel,C.border);txt(c,'“',884,297,124,C.gold,'Genesis Light');wrap(c,s.quote,908,425,837,49,C.text,'Genesis Light',1.26);label(c,'TRY IT IN YOUR CONVERSATION',908,692);wrap(c,s.body,100,487,674,37);wrap(c,s.note,885,810,900,31,C.muted);}
 if(s.kind==='exchange'){rounded(c,852,287,966,212,22,C.panel,C.border);label(c,'A POSSIBLE NEXT QUESTION',884,320);wrap(c,s.question,884,373,895,40);rounded(c,852,534,966,257,22,'#242036','#4c4268');label(c,'YOUR FOLLOW-UP',884,566);wrap(c,s.answer,884,622,895,38);wrap(c,s.body,100,481,677,37);wrap(c,s.note,879,842,912,29,C.muted);}
 });let hero=null;
 if(s.kind==='title')hero=layer(c=>{label(c,s.eyebrow,100,261);wrap(c,s.title,96,327,1250,126,C.text,'Genesis Light',1.06);wrap(c,s.body,103,669,1300,39,C.muted, 'Genesis',1.45);rounded(c,104,842,570,60,30,'#292436','#51416d');txt(c,s.tag,133,854,28,C.text);});
 return {heading,body,screen:s.kind==='screen'?screenLayer(s):null,hero};}
const bg=layer(c=>{c.fillStyle=C.bg;c.fillRect(0,0,W,H);let g=c.createRadialGradient(1590,425,30,1590,425,1100);g.addColorStop(0,'#25203a');g.addColorStop(1,C.bg);c.fillStyle=g;c.fillRect(0,0,W,H);g=c.createRadialGradient(250,1020,0,250,1020,820);g.addColorStop(0,'#26231f');g.addColorStop(1,'#26231f00');c.fillStyle=g;c.fillRect(0,0,W,H);c.strokeStyle='#ffffff06';c.lineWidth=1;for(let x=0;x<W;x+=80){c.beginPath();c.moveTo(x,0);c.lineTo(x,H);c.stroke()}for(let y=0;y<H;y+=80){c.beginPath();c.moveTo(0,y);c.lineTo(W,y);c.stroke()}});
function reveal(img,t,start=.1,duration=.9,dy=26){if(!img)return;let p=ease((t-start)/duration);ctx.save();ctx.globalAlpha=p;ctx.drawImage(img,0,(1-p)*dy);ctx.restore()}
let recordingForeground=false;
function drawOriginal(s,l,t,absolute){if(!recordingForeground){ctx.drawImage(bg,0,0);ctx.save();ctx.globalAlpha=.45;ctx.strokeStyle=C.gold;ctx.lineWidth=1;const cx=s.kind==='title'?1540:1750,cy=s.kind==='title'?565:70;for(const r of [185,255,365]){ctx.beginPath();ctx.arc(cx,cy,r,-.7+absolute*.009,1.6+absolute*.009);ctx.stroke()}ctx.restore();
} ctx.drawImage(logo,96,60,55,55);txt(ctx,'GENESIS AI',168,73,28,C.text,'Genesis Bold');txt(ctx,'KEEP GENESIS YOURS',1387,79,22,C.muted);ctx.fillStyle='#ffffff18';ctx.fillRect(96,147,1728,1);
 if(s.kind==='title'){
  for(const [y,h,delay] of [[248,396,.05],[657,165,.65],[831,94,1.1]]){ctx.save();ctx.beginPath();ctx.rect(80,y,1290,h);ctx.clip();reveal(l.hero,t,delay,1.3,28);ctx.restore()}
  const p=ease((t-.35)/2);ctx.save();ctx.globalAlpha=p;ctx.translate(1540,565);ctx.rotate((1-p)*-.07);ctx.scale(.82+.18*p,.82+.18*p);ctx.shadowColor='#9c7eff50';ctx.shadowBlur=45;ctx.drawImage(logo,-140,-140,280,280);ctx.restore();
 }else{reveal(l.heading,t,.08,.85,24);
  if(s.kind==='list'){ctx.save();ctx.beginPath();ctx.rect(0,420,840,530);ctx.clip();reveal(l.body,t,.3,1.1,24);ctx.restore();for(let i=0;i<s.items.length;i++){ctx.save();ctx.beginPath();ctx.rect(850,334+i*118,990,112);ctx.clip();reveal(l.body,t,.35+i*.18,.8,10);ctx.restore()}}else reveal(l.body,t,.38,1.05,32);
  if(l.screen){let screen=l.screen;if(s.contextZoom&&t<4.5){const p=ease((t-2.8)/1.7),full=[0,0,1600,1000],crop=full.map((v,i)=>v+(s.crop[i]-v)*p);screen=screenLayer(s,crop)}ctx.save();const z=1+.025*(1-ease(t/2.4));ctx.translate(1350,590);ctx.scale(z,z);ctx.translate(-1350,-590);reveal(screen,t,.22,1.25,38);ctx.restore()}}
 if(!recordingForeground){ctx.fillStyle='#ffffff20';ctx.fillRect(96,1024,1728,3);ctx.fillStyle=C.gold;ctx.fillRect(96,1024,1728*absolute/total,3);}
 const chapters=data.progressLabels;for(let i=0;i<data.progressLabels.length;i++){const x=102+i*(1728/data.progressLabels.length);ctx.fillStyle=s.chapter>=i+1?C.gold:'#525767';ctx.beginPath();ctx.arc(x,995,4,0,Math.PI*2);ctx.fill();txt(ctx,chapters[i],x+14,984,17,s.chapter===i+1?C.gold:C.muted)}
 if(!recordingForeground)txt(ctx,`${String(Math.floor(absolute/60)).padStart(2,'0')}:${String(Math.floor(absolute%60)).padStart(2,'0')} / ${Math.floor(total/60)}:${String(total%60).padStart(2,'0')}`,1600,1040,17,C.muted);
 if(t>s.duration-.55){ctx.fillStyle=`rgba(12,14,22,${ease((t-(s.duration-.55))/.55)})`;ctx.fillRect(0,160,W,820)}
}
function draw(s,l,t,absolute){
 if(t<4.5){drawOriginal(s,l,t,absolute);return}
 if(!l.settledForeground){ctx.clearRect(0,0,W,H);recordingForeground=true;drawOriginal(s,l,5,0);recordingForeground=false;l.settledForeground=createCanvas(W,H);l.settledForeground.getContext('2d').drawImage(canvas,0,0)}
 ctx.drawImage(bg,0,0);ctx.save();ctx.globalAlpha=.45;ctx.strokeStyle=C.gold;ctx.lineWidth=1;const cx=s.kind==='title'?1540:1750,cy=s.kind==='title'?565:70;for(const r of [185,255,365]){ctx.beginPath();ctx.arc(cx,cy,r,-.7+absolute*.009,1.6+absolute*.009);ctx.stroke()}ctx.restore();

 ctx.drawImage(l.settledForeground,0,0);
 ctx.fillStyle='#ffffff20';ctx.fillRect(96,1024,1728,3);ctx.fillStyle=C.gold;ctx.fillRect(96,1024,1728*absolute/total,3);
 txt(ctx,`${String(Math.floor(absolute/60)).padStart(2,'0')}:${String(Math.floor(absolute%60)).padStart(2,'0')} / ${Math.floor(total/60)}:${String(total%60).padStart(2,'0')}`,1600,1040,17,C.muted);
 if(t>s.duration-.55){ctx.fillStyle=`rgba(12,14,22,${ease((t-(s.duration-.55))/.55)})`;ctx.fillRect(0,160,W,820)}
}
async function init(){logo=await loadImage(path.join(assets,'brand/genesis.png'));for(const name of [...new Set(data.scenes.filter(s=>s.screen).map(s=>s.screen))])images[name]=await loadImage(name.startsWith('@video7/')?path.join(root,'assets/video7/screens',name.slice(8)+'.png'):path.join(assets,'screens',name+'.png'));}
function writeMetadata(){let start=0;const lines=['# '+data.title+' — editable video 7','',`Duration: ${total} seconds. 1920×1080 / 30 fps. Text + owner-selected music.`, '','Screenshots are clean demonstration fixtures. Illustrative dialogue is labelled; no live model result is claimed.','','## Script and coverage',''];const chapters=[';FFMETADATA1','title=Genesis AI — '+data.title];const starts={};const coverage=[];for(const [i,s]of data.scenes.entries()){if(starts[s.chapter]===undefined)starts[s.chapter]=start;coverage.push({scene:i+1,start,end:start+s.duration,step:s.chapter,lesson:s.lesson,sourceSteps:s.sourceSteps,checkpointSteps:s.checkpointSteps||[],readingWords:s.readingWords,readingSeconds:s.readingSeconds,locateSeconds:s.locateSeconds,title:s.title,kind:s.kind,screenshot:s.screen||null,crop:s.crop||null,highlight:s.highlight||null,words:(s.body||s.note||'').split(/\s+/).length});lines.push(`### ${Math.floor(start/60)}:${String(start%60).padStart(2,'0')} — ${s.title.replaceAll('\n',' ')}`,`Hold: ${s.duration} seconds.`,s.body||'',s.quote||'',s.question||'',s.answer||'',...(s.items||[]),...(s.cards||[]).map(c=>c.title+': '+c.body),s.note||'','');start+=s.duration}const entries=Object.entries(starts);for(let i=0;i<entries.length;i++){const [n,t]=entries[i];chapters.push('[CHAPTER]','TIMEBASE=1/1000',`START=${t*1000}`,`END=${(entries[i+1]?.[1]??total)*1000}`,`title=${data.chapters[n]}`)}fs.writeFileSync(path.join(output,'script-and-chapters.md'),lines.join('\n'));fs.writeFileSync(path.join(output,'coverage.json'),JSON.stringify({lessons:data.lessonIds,total,chapters:data.chapters,sourceLessons:data.sourceLessons,scenes:coverage},null,2));fs.writeFileSync(path.join(output,'chapters.ffmeta'),chapters.join('\n'));}
async function main(){await init();writeMetadata();const preview=process.argv.includes('--preview');let absolute=0;
 const thumbs=createCanvas(960*3,540*Math.ceil(data.scenes.length/3)),tc=thumbs.getContext('2d');for(let i=0;i<data.scenes.length;i++){draw(data.scenes[i],makeLayers(data.scenes[i]),5,absolute+5);fs.writeFileSync(path.join(output,`scene-${String(i+1).padStart(2,'0')}.png`),canvas.toBuffer('image/png'));tc.drawImage(canvas,i%3*960,Math.floor(i/3)*540,960,540);absolute+=data.scenes[i].duration}fs.writeFileSync(path.join(output,'storyboard.jpg'),thumbs.toBuffer('image/jpeg',85));if(preview){console.log(JSON.stringify({total,scenes:data.scenes.length,output}));return}
 const log=fs.openSync(path.join(output,'encode.log'),'w');const silent=path.join(output,'picture.mp4');const encoder=cp.spawn(ffmpeg,['-y','-hide_banner','-f','rawvideo','-pixel_format','rgba','-video_size',`${W}x${H}`,'-framerate',String(FPS),'-i','pipe:0','-an','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-threads','6','-movflags','+faststart',silent],{stdio:['pipe','ignore',log],windowsHide:true});encoder.stdin.on('error',e=>console.error(e.message));absolute=0;let frame=0;for(let i=0;i<data.scenes.length;i++){const sceneLayers=makeLayers(data.scenes[i]);console.log(`Rendering ${i+1}/${data.scenes.length}: ${data.scenes[i].title.replaceAll('\n',' ')}`);for(let j=0;j<data.scenes[i].duration*FPS;j++){draw(data.scenes[i],sceneLayers,j/FPS,absolute+j/FPS);if(!encoder.stdin.write(canvas.data()))await once(encoder.stdin,'drain');frame++;if(global.gc&&frame%30===0)global.gc()}absolute+=data.scenes[i].duration}encoder.stdin.end();const [code]=await once(encoder,'close');fs.closeSync(log);if(code!==0)throw Error('Picture encoding failed: '+code);
 const final=path.join(output,data.filename);const musicInfo=cp.spawnSync(ffmpeg,['-hide_banner','-i',data.music],{encoding:'utf8',windowsHide:true}).stderr;
 const m=/Duration: (\d+):(\d+):(\d+\.\d+)/.exec(musicInfo);if(!m)throw Error('Music duration unavailable');
 const musicDuration=Number(m[1])*3600+Number(m[2])*60+Number(m[3]);
 const {crossfade,repeatStart,trimEnd,fadeIn,fadeOut,rationale}=data.audio;
 const repeatDuration=trimEnd-repeatStart,loopCount=1+Math.max(0,Math.ceil((total-trimEnd)/(repeatDuration-crossfade)));
 const args=['-y','-hide_banner','-i',silent];for(let n=0;n<loopCount;n++)args.push('-i',data.music);args.push('-i',path.join(output,'chapters.ffmeta'));
 const filters=[];for(let n=1;n<=loopCount;n++)filters.push('['+n+':a]atrim=start='+(n===1?0:repeatStart)+':end='+trimEnd+',asetpts=PTS-STARTPTS[a'+n+']');let previous='a1';
 for(let n=2;n<=loopCount;n++){const next='join'+n;filters.push('['+previous+'][a'+n+']acrossfade=d='+crossfade+':c1=qsin:c2=qsin['+next+']');previous=next;}
 filters.push('['+previous+']loudnorm=I=-20:TP=-2:LRA=9,afade=t=in:st=0:d='+fadeIn+',afade=t=out:st='+(total-fadeOut)+':d='+fadeOut+'[a]');
 args.push('-filter_complex',filters.join(';'),'-map','0:v:0','-map','[a]','-map_metadata',String(loopCount+1),'-map_chapters',String(loopCount+1),'-t',String(total),'-c:v','copy','-c:a','aac','-b:a','192k','-ar','48000','-movflags','+faststart',final);
 fs.writeFileSync(path.join(output,'audio-plan.json'),JSON.stringify({music:data.music,musicDuration,total,crossfade,repeatStart,trimEnd,repeatDuration,curve:'equal-power qsin',loopCount,bedDuration:trimEnd+(loopCount-1)*(repeatDuration-crossfade),joins:Array.from({length:loopCount-1},(_,i)=>({start:trimEnd-crossfade+i*(repeatDuration-crossfade),end:trimEnd+i*(repeatDuration-crossfade)})),fadeIn,fadeOut,targetLUFS:-20,rationale},null,2));
 const mix=cp.spawnSync(ffmpeg,args,{encoding:'utf8',windowsHide:true});fs.writeFileSync(path.join(output,'mix.log'),mix.stderr||'');if(mix.status!==0)throw Error('Audio mux failed');console.log('FINISHED '+final);}
main().catch(e=>{console.error(e);process.exit(1)});
