const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=__dirname,out=path.join(root,'output/video-06'),evidence=path.resolve(root,'../../../Claude and OpenAI docs/Genesis-Knowledge/evidence/tutorial-video-6-20261003');
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(evidence,{recursive:true});
function hash(file){const h=crypto.createHash('sha256'),fd=fs.openSync(file,'r'),b=Buffer.alloc(1048576);try{let n;while(n=fs.readSync(fd,b,0,b.length,null))h.update(b.subarray(0,n))}finally{fs.closeSync(fd)}return h.digest('hex')}
if(!fs.existsSync(path.join(evidence,'preservation-baseline.json'))){let files=[];function walk(d){for(const n of fs.readdirSync(d)){const f=path.join(d,n);if(fs.statSync(f).isDirectory())walk(f);else files.push(f)}}for(const n of fs.readdirSync(root)){const f=path.join(root,n);if(fs.statSync(f).isFile()&&!n.includes('video6'))files.push(f)}for(const d of ['output/video-02','output/video-03','output/video-04','output/video-05','assets'])walk(path.join(root,d));walk(path.resolve(root,'../tutorials/assets'));files.push(path.join(root,'output/Genesis-Your-First-Five-Minutes.mp4'));walk('C:/Development-Gen/Publish/youtube videos');fs.writeFileSync(path.join(evidence,'preservation-baseline.json'),JSON.stringify({createdAt:new Date().toISOString(),files:files.map(file=>({file,sha256:hash(file)}))},null,2));}
for(const stem of ['qa','layout-check','audio','native-frames','review-frames','export-coverage','render','verify','finalize']){let c=fs.readFileSync(path.join(root,stem+'-video5.cjs'),'utf8').replaceAll('video5','video6').replaceAll('video-05','video-06').replaceAll('video-5-20261003','video-6-20261003').replaceAll('Genesis-Turn-Ideas-Into-Finished-Work','Genesis-Open-Up-The-Possibilities').replaceAll('Turn ideas into finished work','Open up the possibilities').replaceAll('IDEAS INTO FINISHED WORK','OPEN UP THE POSSIBILITIES').replaceAll('Video 5','Video 6').replaceAll('video 5','video 6');
if(stem==='verify')c=c.replaceAll('length!==7','length!==10');
if(stem==='finalize')c=c.replace('05 - Genesis - Turn Ideas Into Finished Work.mp4','06 - Genesis - Open Up The Possibilities.mp4').replace('chapters.length!==7','chapters.length!==10').replace('exactSourceText.length!==45','exactSourceText.length!==44').replace('steps:45','steps:44');
if(stem==='export-coverage')c=c.replaceAll('45 steps','44 steps').replaceAll('category 4','category 5');
const f=path.join(root,stem+'-video6.cjs');if(fs.existsSync(f))throw Error('Preserve existing '+f);fs.writeFileSync(f,c)}
let player=fs.readFileSync(path.join(root,'review-video5.html'),'utf8').replaceAll('Video 5','Video 6').replaceAll('video-05','video-06').replaceAll('Genesis-Turn-Ideas-Into-Finished-Work','Genesis-Open-Up-The-Possibilities').replaceAll('Turn ideas into finished work','Open up the possibilities').replaceAll('category 4','category 5').replaceAll('six lessons','nine lessons');fs.writeFileSync(path.join(root,'review-video6.html'),player);
fs.writeFileSync(path.join(root,'timeline-video6.json'),JSON.stringify({music:'C:/Development-Gen/songs/Video 6 song.mp3',audio:{rationale:'Source analysis pending; do not render until measured arrangement is set.'}},null,2));
console.log('Preserved earlier artifacts; created isolated video 6 pipeline');
