const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=__dirname,out=path.join(root,'output/video-05'),evidence=path.resolve(root,'../../../Claude and OpenAI docs/Genesis-Knowledge/evidence/tutorial-video-5-20261003');
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(evidence,{recursive:true});
function hash(f){const h=crypto.createHash('sha256'),fd=fs.openSync(f,'r'),b=Buffer.alloc(1048576);try{let n;while((n=fs.readSync(fd,b,0,b.length,null)))h.update(b.subarray(0,n));}finally{fs.closeSync(fd)}return h.digest('hex')}
if(!fs.existsSync(path.join(evidence,'preservation-baseline.json'))){const files=[];function walk(d){for(const n of fs.readdirSync(d)){const f=path.join(d,n);if(fs.statSync(f).isDirectory())walk(f);else files.push(f)}}
for(const n of fs.readdirSync(root)){const f=path.join(root,n);if(fs.statSync(f).isFile()&&!n.includes('video5'))files.push(f)}
for(const d of ['output/video-02','output/video-03','output/video-04','assets'])walk(path.join(root,d));walk(path.resolve(root,'../tutorials/assets'));files.push(path.join(root,'output/Genesis-Your-First-Five-Minutes.mp4'));walk('C:/Development-Gen/Publish/youtube videos');
fs.writeFileSync(path.join(evidence,'preservation-baseline.json'),JSON.stringify({createdAt:new Date().toISOString(),files:[...new Set(files)].map(file=>({file,sha256:hash(file)}))},null,2));}
for(const stem of ['qa','layout-check','audio','native-frames','review-frames','export-coverage','render','verify','finalize']){let code=fs.readFileSync(path.join(root,stem+'-video4.cjs'),'utf8').replaceAll('video4','video5').replaceAll('video-04','video-05').replaceAll('video-4-20261002','video-5-20261003').replaceAll('Genesis-Speak-Listen-See','Genesis-Turn-Ideas-Into-Finished-Work').replaceAll('Speak. Listen. See.','Turn ideas into finished work').replaceAll('SPEAK. LISTEN. SEE.','IDEAS INTO FINISHED WORK').replaceAll('Video 4','Video 5').replaceAll('video 4','video 5').replaceAll('2026-10-02','2026-10-03');
if(stem==='verify')code=code.replace('.length!==8)', '.length!==7)').replace('length!==8)', 'length!==7)').replace("JSON.parse(fs.readFileSync(path.join(root,'assets/video5/screens.json')))","{screens:{}}");
if(stem==='finalize')code=code.replace('04 - Genesis - Speak Listen See.mp4','05 - Genesis - Turn Ideas Into Finished Work.mp4').replace('chapters.length!==8','chapters.length!==7').replace('exactSourceText.length!==37','exactSourceText.length!==45').replace('steps:37','steps:45');
if(stem==='export-coverage')code=code.replaceAll('37 steps','45 steps').replaceAll('category 3','category 4');
const f=path.join(root,stem+'-video5.cjs');if(fs.existsSync(f))throw Error('Preserve existing '+f);fs.writeFileSync(f,code);}
let player=fs.readFileSync(path.join(root,'review-video4.html'),'utf8').replaceAll('Video 4','Video 5').replaceAll('video-04','video-05').replaceAll('Genesis-Speak-Listen-See','Genesis-Turn-Ideas-Into-Finished-Work').replaceAll('Speak. Listen. See.','Turn ideas into finished work').replaceAll('category 3','category 4').replaceAll('seven lessons','six lessons');fs.writeFileSync(path.join(root,'review-video5.html'),player);
console.log('Video 5 preserved baseline and isolated pipeline created');
