const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const {chromium}=require('C:/Users/damir/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=__dirname,out=path.join(root,'output'),evidence=path.resolve(root,'../../../Claude and OpenAI docs/Genesis-Knowledge/evidence/tutorial-video-20261002');fs.mkdirSync(evidence,{recursive:true});
const file=path.join(out,'Genesis-Your-First-Five-Minutes.mp4'),ffmpeg=fs.readdirSync(path.join(root,'vendor/imageio_ffmpeg/binaries')).filter(n=>n.endsWith('.exe')).map(n=>path.join(root,'vendor/imageio_ffmpeg/binaries',n))[0];
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function main(){for(let i=0;i<900&&!fs.existsSync(path.join(out,'mix.log'));i++)await delay(2000);if(!fs.existsSync(file))throw Error('No finished video');
const data=JSON.parse(fs.readFileSync(path.join(out,'coverage.json'),'utf8'));const source=JSON.parse(fs.readFileSync(path.resolve(root,'../tutorials/assets/screens.json'),'utf8'));const hashes=[];for(const n of [...new Set(data.scenes.filter(s=>s.screenshot).map(s=>s.screenshot))]){const hash=crypto.createHash('sha256').update(fs.readFileSync(path.resolve(root,'../tutorials/assets/screens',n+'.png'))).digest('hex');hashes.push({name:n,match:hash===source.screens[n].sha256,sha256:hash});if(!hashes.at(-1).match)throw Error('Original screenshot changed')}
const decode=cp.spawnSync(ffmpeg,['-v','error','-xerror','-i',file,'-map','0:v','-map','0:a','-f','null','-'],{encoding:'utf8',windowsHide:true});if(decode.status!==0)throw Error('Decode failed: '+decode.stderr);
const metadata=cp.spawnSync(ffmpeg,['-hide_banner','-i',file],{encoding:'utf8',windowsHide:true}).stderr;fs.writeFileSync(path.join(evidence,'encoded-metadata.txt'),metadata);
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage({viewport:{width:1440,height:1040}});await page.goto('http://127.0.0.1:4186/video-production/review.html');await page.waitForFunction(()=>document.querySelector('video').readyState>=2);const info=await page.evaluate(()=>{let v=document.querySelector('video');return {duration:v.duration,width:v.videoWidth,height:v.videoHeight,codecSupport:v.canPlayType('video/mp4; codecs="avc1.640028, mp4a.40.2"')}});if(info.duration!==data.total||info.width!==1920||info.height!==1080)throw Error('Unexpected media dimensions/duration');await page.evaluate(()=>document.querySelector('video').play());console.log('Full normal-speed playback started: '+data.total+'s');
let seen=new Set,lastTime=0,lastAdvance=Date.now(),finished=false;while(!finished){await delay(1000);const state=await page.evaluate(()=>{const v=document.querySelector('video');return {time:v.currentTime,ended:v.ended,error:v.error?.message||null,ready:v.readyState}});if(state.error)throw Error(state.error);if(state.time>lastTime+.1){lastAdvance=Date.now();lastTime=state.time}if(Date.now()-lastAdvance>15000)throw Error('Playback stalled');for(const [i,s]of data.scenes.entries()){if(state.time>=s.start+4&&!seen.has(i)){seen.add(i);await page.locator('video').screenshot({path:path.join(evidence,`playback-scene-${String(i+1).padStart(2,'0')}.png`)});console.log(`Watched ${i+1}/${data.scenes.length} at ${state.time.toFixed(1)}s`);}}finished=state.ended;}
const playback=await page.evaluate(()=>playbackEvidence);await page.screenshot({path:path.join(evidence,'desktop-player.png')});await page.setViewportSize({width:852,height:650});await page.evaluate(()=>{const v=document.querySelector('video');v.currentTime=140});await page.waitForFunction(()=>Math.abs(document.querySelector('video').currentTime-140)<.1&&!document.querySelector('video').seeking);await page.screenshot({path:path.join(evidence,'phone-landscape-player.png')});
fs.writeFileSync(path.join(evidence,'verification.json'),JSON.stringify({date:'2026-10-02',decode:{exitCode:decode.status,errors:decode.stderr},info,sourceHashes:hashes,coverage:data,normalSpeedPlayback:playback,sceneFrames:seen.size,videoSha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),limitations:['Text and music; no spoken narration.','UI screenshots use clean demonstration data; illustrative dialogue is labelled.','Owner style and pacing review pending.']},null,2));await browser.close();console.log('VERIFIED '+path.join(evidence,'verification.json'));}
main().catch(e=>{console.error(e);process.exit(1)});
