const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const {chromium}=require('C:/Users/damir/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=__dirname,out=path.join(root,'output/video-07'),evidence=path.resolve(root,'../../../Claude and OpenAI docs/Genesis-Knowledge/evidence/tutorial-video-7-20261003');
const file=path.join(out,'Genesis-Keep-Genesis-Yours.mp4'),ffmpeg=path.join(root,'vendor/imageio_ffmpeg/binaries',fs.readdirSync(path.join(root,'vendor/imageio_ffmpeg/binaries')).find(n=>n.endsWith('.exe')));
const delay=ms=>new Promise(r=>setTimeout(r,ms)),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
function containerAtoms(file){const fd=fs.openSync(file,'r'),length=fs.statSync(file).size,atoms=[];try{let at=0;while(at<length){const header=Buffer.alloc(16);fs.readSync(fd,header,0,Math.min(16,length-at),at);let size=header.readUInt32BE(0);if(size===1)size=Number(header.readBigUInt64BE(8));else if(size===0)size=length-at;if(size<8||at+size>length)throw Error('Invalid MP4 atom');atoms.push({type:header.toString('ascii',4,8),offset:at,size});at+=size;}}finally{fs.closeSync(fd)}return atoms;}
let reviewServer,browserOwned;
async function startServer(){const http=require('node:http'),serveRoot=path.resolve(root,'..');reviewServer=http.createServer((req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://127.0.0.1').pathname),filePath=path.resolve(serveRoot,'.'+pathname);if(!filePath.startsWith(serveRoot+path.sep)||!fs.existsSync(filePath)||!fs.statSync(filePath).isFile()){res.writeHead(404);return res.end()}const size=fs.statSync(filePath).size,types={'.html':'text/html','.json':'application/json','.png':'image/png','.mp4':'video/mp4'};let start=0,end=size-1,status=200;const headers={'Content-Type':types[path.extname(filePath)]||'application/octet-stream','Accept-Ranges':'bytes'};if(req.headers.range){const m=/bytes=(\d+)-(\d*)/.exec(req.headers.range);if(!m){res.writeHead(416);return res.end()}start=Number(m[1]);end=Math.min(m[2]?Number(m[2]):size-1,size-1);if(start>end){res.writeHead(416);return res.end()}status=206;headers['Content-Range']='bytes '+start+'-'+end+'/'+size}headers['Content-Length']=end-start+1;res.writeHead(status,headers);const stream=fs.createReadStream(filePath,{start,end});stream.on('error',()=>res.destroy());res.on('close',()=>stream.destroy());stream.pipe(res)}catch(e){res.writeHead(500);res.end(e.message)}});await new Promise((resolve,reject)=>{reviewServer.once('error',reject);reviewServer.listen(0,'127.0.0.1',resolve)});return reviewServer.address().port;}
async function main(){fs.mkdirSync(evidence,{recursive:true});if(!fs.existsSync(file))throw Error('Master missing');const data=JSON.parse(fs.readFileSync(path.join(out,'coverage.json')));
const source=JSON.parse(fs.readFileSync(path.resolve(root,'../tutorials/assets/screens.json'))),extra=JSON.parse(fs.readFileSync(path.join(root,'assets/video7/screens.json'))),preflight=JSON.parse(fs.readFileSync(path.join(evidence,'preflight.json')));
const hashes=[];for(const n of [...new Set(data.scenes.filter(s=>s.screenshot).map(s=>s.screenshot))]){const isExtra=n.startsWith('@video7/'),name=isExtra?n.slice(8):n,f=isExtra?path.join(root,'assets/video7/screens',name+'.png'):path.resolve(root,'../tutorials/assets/screens',name+'.png'),sha256=hash(f),expected=(isExtra?extra:source).screens[name].sha256;hashes.push({name:n,sha256,match:sha256===expected});if(sha256!==expected)throw Error('Source hash mismatch: '+n)}
const allOriginalHashes=Object.entries(source.screens).map(([name,s])=>({name,sha256:hash(path.resolve(root,'../tutorials/assets/screens',s.file)),expected:s.sha256}));if(allOriginalHashes.some(s=>s.sha256!==s.expected))throw Error('An original catalog screenshot changed');fs.writeFileSync(path.join(evidence,'all-original-screen-hashes.json'),JSON.stringify(allOriginalHashes,null,2));
const pilot=Object.entries(preflight.files).map(([name,sha256])=>({name,sha256,unchanged:hash(path.join(root,name))===sha256}));if(pilot.some(p=>!p.unchanged)||hash('C:/Development-Gen/songs/video 1 song.MP3')!==preflight.songSha256)throw Error('Pilot or soundtrack changed');
const phoneIndices=Array.from({length:10},(_,i)=>Math.min(data.scenes.length-1,Math.floor((i+.5)*data.scenes.length/10)));
const port=await startServer();const browser=browserOwned=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--autoplay-policy=no-user-gesture-required','--disable-background-timer-throttling','--disable-renderer-backgrounding']});const page=await browser.newPage({viewport:{width:1440,height:1040}});
await page.goto('http://127.0.0.1:'+port+'/video-production/review-video7.html');await page.waitForFunction(()=>document.querySelector('video').readyState>=2);
const info=await page.evaluate(()=>{const v=document.querySelector('video');return{duration:v.duration,width:v.videoWidth,height:v.videoHeight,codecSupport:v.canPlayType('video/mp4; codecs="avc1.640028, mp4a.40.2"'),audioTracks:v.webkitAudioDecodedByteCount}});if(info.duration!==data.total||info.width!==1920||info.height!==1080)throw Error('Media dimensions/duration');
// Whole-file decode and audio analysis run independently of normal-speed playback.
const decode=cp.spawn(ffmpeg,['-v','error','-xerror','-threads','4','-i',file,'-map','0:v','-map','0:a','-f','null','-'],{windowsHide:true,stdio:['ignore','ignore','pipe']});let decodeErrors='';decode.stderr.on('data',b=>decodeErrors+=b);const decodeResult=new Promise(resolve=>decode.on('close',code=>resolve({exitCode:code,errors:decodeErrors})));
const audio=cp.spawn(process.execPath,[path.join(root,'audio-video7.cjs')],{windowsHide:true,stdio:['ignore',fs.openSync(path.join(out,'audio-check.log'),'w'),fs.openSync(path.join(out,'audio-check-error.log'),'w')]});const audioResult=new Promise(resolve=>audio.on('close',code=>resolve(code)));
const metadata=cp.spawnSync(ffmpeg,['-hide_banner','-i',file],{encoding:'utf8',windowsHide:true}).stderr;fs.writeFileSync(path.join(evidence,'encoded-metadata.txt'),metadata);
if(!/Video: h264 \(High\)/.test(metadata)||!/yuv420p/.test(metadata)||!/1920x1080/.test(metadata)||!/30 fps/.test(metadata)||!/Audio: aac \(LC\)/.test(metadata)||!/48000 Hz, stereo/.test(metadata)||(metadata.match(/Chapter #/g)||[]).length!==7)throw Error('Encoding/chapter metadata mismatch');
const atoms=containerAtoms(file),faststart=atoms.find(a=>a.type==='moov')?.offset<atoms.find(a=>a.type==='mdat')?.offset;if(!faststart)throw Error('MP4 faststart missing');
const chapterMetadata=[...metadata.matchAll(/Chapter #\d+:\d+: start ([\d.]+), end ([\d.]+)\s+Metadata:\s+title\s*:\s*([^\r\n]+)/g)].map(m=>({start:Number(m[1]),end:Number(m[2]),title:m[3].trim()}));const chapterScenes=data.scenes.filter((s,i,a)=>i===0||s.step!==a[i-1].step);
if(chapterMetadata.length!==chapterScenes.length||chapterMetadata.some((c,i)=>Math.abs(c.start-chapterScenes[i].start)>.001||c.title!==data.chapters[chapterScenes[i].step]))throw Error('Embedded chapter times/titles mismatch');
fs.writeFileSync(path.join(evidence,'container-validation.json'),JSON.stringify({faststart,atoms,chapters:chapterMetadata,videoSha256:hash(file)},null,2));
await page.evaluate(()=>{const v=document.querySelector('video');v.muted=false;v.volume=1;v.playbackRate=1;return v.play()});console.log('Normal-speed playback started: '+data.total+' seconds');
let seen=new Set,lastTime=0,lastAdvance=Date.now(),finished=false;while(!finished){await delay(1000);const state=await page.evaluate(()=>{const v=document.querySelector('video');return {time:v.currentTime,ended:v.ended,error:v.error?.message||null,ready:v.readyState,paused:v.paused,muted:v.muted,rate:v.playbackRate,audioBytes:v.webkitAudioDecodedByteCount}});if(state.error||state.muted||state.rate!==1||(state.paused&&!state.ended))throw Error('Playback error: '+JSON.stringify(state));if(state.time>lastTime+.1){lastAdvance=Date.now();lastTime=state.time}if(Date.now()-lastAdvance>20000)throw Error('Playback stalled');for(const [i,s]of data.scenes.entries())if(state.time>=s.start+5&&!seen.has(i)){seen.add(i);await page.locator('video').screenshot({path:path.join(evidence,`playback-scene-${String(i+1).padStart(2,'0')}.png`)});console.log(`Watched ${i+1}/${data.scenes.length} at ${state.time.toFixed(1)}s`);}fs.writeFileSync(path.join(evidence,'playback-progress.json'),JSON.stringify({...state,beats:seen.size,totalBeats:data.scenes.length,checkedAt:new Date().toISOString()}));finished=state.ended;}
const playback=await page.evaluate(()=>{const v=document.querySelector('video'),q=v.getVideoPlaybackQuality();return {...playbackEvidence,quality:{totalVideoFrames:q.totalVideoFrames,droppedVideoFrames:q.droppedVideoFrames,corruptedVideoFrames:q.corruptedVideoFrames},audioDecodedBytes:v.webkitAudioDecodedByteCount,muted:v.muted,playbackRate:v.playbackRate}});
await page.screenshot({path:path.join(evidence,'desktop-player.png')});
// Inspect encoded transition state on both sides of every cut, without changing the complete-playback evidence.
for(let i=1;i<data.scenes.length;i++){const time=data.scenes[i].start;for(const [label,offset]of [['out',-.2],['in',.25]]){await page.evaluate(t=>{document.querySelector('video').currentTime=t},time+offset);await page.waitForFunction(()=>!document.querySelector('video').seeking);await page.locator('video').screenshot({path:path.join(evidence,`transition-${String(i).padStart(2,'0')}-${label}.png`)});}}
await page.setViewportSize({width:520,height:620});for(const i of phoneIndices){await page.evaluate(t=>{document.querySelector('video').currentTime=t},data.scenes[i].start+6);await page.waitForFunction(()=>!document.querySelector('video').seeking);await page.screenshot({path:path.join(evidence,`phone-beat-${i+1}.png`)});}
await page.setViewportSize({width:854,height:480});for(const i of phoneIndices){await page.evaluate(t=>{document.querySelector('video').currentTime=t},data.scenes[i].start+6);await page.waitForFunction(()=>!document.querySelector('video').seeking);await page.locator('video').screenshot({path:path.join(evidence,`phone-landscape-beat-${i+1}.png`)});}
// Chapter controls and the self-contained local-file player are checked after complete playback.
const chapterButtons=page.locator('#chapters button');if(await chapterButtons.count()!==7)throw Error('Player chapter count');const navigation=[];
for(let i=0;i<chapterScenes.length;i++){await chapterButtons.nth(i).click();await page.waitForFunction(()=>!document.querySelector('video').seeking);const state=await page.evaluate(()=>{const v=document.querySelector('video');v.pause();return {time:v.currentTime,error:v.error?.message||null}});if(state.error||Math.abs(state.time-chapterScenes[i].start)>2)throw Error('Chapter navigation mismatch');navigation.push({title:data.chapters[chapterScenes[i].step],expected:chapterScenes[i].start,actual:state.time});}
const offline=await browser.newPage({viewport:{width:1440,height:1040}});await offline.goto(require('node:url').pathToFileURL(path.join(root,'review-video7.html')).href);await offline.waitForFunction(()=>document.querySelector('video').readyState>=2);if(await offline.locator('#chapters button').count()!==7)throw Error('Local player chapters missing');await offline.evaluate(()=>document.querySelector('video').play());await delay(1800);const localPlayer=await offline.evaluate(()=>{const v=document.querySelector('video');v.pause();return {time:v.currentTime,error:v.error?.message||null,width:v.videoWidth,height:v.videoHeight,audioBytes:v.webkitAudioDecodedByteCount}});if(localPlayer.error||localPlayer.time<1||localPlayer.audioBytes<=0)throw Error('Local player failed');await offline.screenshot({path:path.join(evidence,'local-file-player.png')});await offline.close();fs.writeFileSync(path.join(evidence,'player-validation.json'),JSON.stringify({videoSha256:hash(file),navigation,localPlayer},null,2));
const decoded=await decodeResult;if(decoded.exitCode!==0)throw Error('Decode failed: '+decoded.errors);if(await audioResult!==0)throw Error('Audio verification failed');if(seen.size!==data.scenes.length||!playback.finishedAt||playback.audioDecodedBytes<=0||playback.events.some(e=>e.event==='seeking'||e.event==='error')||playback.samples.some(s=>s.ready<2))throw Error('Incomplete playback');
const result={date:'2026-10-03',decode:decoded,info,sourceHashes:hashes,pilotPreservation:pilot,coverage:data,normalSpeedPlayback:playback,sceneFrames:seen.size,transitionFrames:(data.scenes.length-1)*2,phoneFrames:20,phoneViewports:[{width:520,height:620,orientation:'portrait',captures:10},{width:854,height:480,orientation:'landscape',captures:10}],videoSha256:hash(file),fileBytes:fs.statSync(file).size,limitations:['Text and music; no spoken narration.','UI screenshot fixtures and illustrative examples; no live model/provider acceptance.','Instrumented audio verification, without subjective continuous listening.','Owner final review pending.']};fs.writeFileSync(path.join(evidence,'verification.json'),JSON.stringify(result,null,2));await browser.close();await new Promise(resolve=>reviewServer.close(resolve));console.log('VERIFIED '+path.join(evidence,'verification.json'));}
main().catch(async e=>{console.error(e);await browserOwned?.close().catch(()=>{});reviewServer?.close();process.exit(1)});
