const {app,BrowserWindow}=require('electron');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),workspace=path.resolve(root,'../../..');
const evidence=path.join(workspace,'Claude and OpenAI docs/Genesis-Knowledge/evidence/tutorials-20261002/shell-integration');
fs.mkdirSync(evidence,{recursive:true});app.setPath('userData',path.join(workspace,'Development/Genesis/.audit-runtime/tutorial-verification'));
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{try{let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(p.endsWith('/'))p+='index.html';const f=path.resolve(root,'.'+p);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end()}res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res)}catch{res.writeHead(400);res.end()}});
const delay=ms=>new Promise(r=>setTimeout(r,ms));let win;const js=s=>win.webContents.executeJavaScript(s);
 const report={date:'2026-10-02',scope:'Local tutorial Chromium interaction and layout, including continuous lesson navigation, universal chooser, unobscured annotations, standard brand, Missions and Work choices. Genesis model/provider behaviour is source-grounded, not live acceptance.',assertions:[],errors:[],missingAnchors:[]};
const check=(name,pass,detail='')=>{report.assertions.push({name,pass:!!pass,detail});if(!pass)throw Error(name+': '+detail)};
async function ready(){for(let i=0;i<100;i++){if(await js('!!window.tutorialGuide'))return;await delay(50)}throw Error('Guide did not initialize')}
async function shot(name){await delay(650);win.webContents.invalidate();await delay(100);fs.writeFileSync(path.join(evidence,name+'.png'),(await win.webContents.capturePage()).toPNG())}
// Space navigation to stay below Chromium's IPC flood protection during a full route sweep.
async function route(id,n=1){await delay(70);await js(`location.hash='#lesson/${id}/${n}'`);for(let i=0;i<100;i++){if(await js(`window.tutorialGuide.getCurrent()?.l.id===${JSON.stringify(id)}&&window.tutorialGuide.getCurrent()?.i===${n-1}`))return;await delay(20)}throw Error('Route did not settle: '+id+'/'+n)}
async function clickAdvance(id,n){await delay(70);await js(`document.querySelector('[data-action="next"]').click()`);for(let i=0;i<100;i++){if(await js(`window.tutorialGuide.getCurrent()?.l.id===${JSON.stringify(id)}&&window.tutorialGuide.getCurrent()?.i===${n-1}`))return;await delay(20)}throw Error('Next did not reach: '+id+'/'+n)}
async function inspectLesson(){return js(`(()=>{
 const g=window.tutorialGuide,c=g.getCurrent(),a=g.resolveAnchor(c.l.steps[c.i]),m=g.manifest.screens[c.l.steps[c.i].screen],rect=document.querySelector('.screen-target'),screen=document.querySelector('.screen-stage').getBoundingClientRect(),r=rect.getBoundingClientRect(),label=document.querySelector('.annotation-label').getBoundingClientRect(),instruction=document.querySelector('.instruction').getBoundingClientRect(),panel=document.querySelector('.course-panel').getBoundingClientRect(),arrow=document.querySelector('.pointer-line'),end=arrow.getPointAtLength(arrow.getTotalLength());
 const px=(r.left-screen.left)/screen.width*m.width,py=(r.top-screen.top)/screen.height*m.height,rw=r.width/screen.width*m.width,rh=r.height/screen.height*m.height;
 const surrounds=px<=a.x-a.w/2+.1&&py<=a.y-a.h/2+.1&&px+rw>=a.x+a.w/2-.1&&py+rh>=a.y+a.h/2-.1;
 // Compare within half a displayed pixel: CSS boxes snap to layout subpixels,
 // while SVG endpoints retain source coordinates at narrow viewport scales.
 const tolerance=.5*m.width/screen.width;
 const arrowAtEdge=(Math.abs(end.x-px)<tolerance||Math.abs(end.x-(px+rw))<tolerance||Math.abs(end.y-py)<tolerance||Math.abs(end.y-(py+rh))<tolerance)&&end.x>=px-tolerance&&end.x<=px+rw+tolerance&&end.y>=py-tolerance&&end.y<=py+rh+tolerance;
 return {surrounds,lineAtEdge:arrowAtEdge,noArrowhead:!arrow.hasAttribute('marker-end')&&!document.querySelector('.annotation-arrow marker'),clear:getComputedStyle(rect).backgroundColor==='rgba(0, 0, 0, 0)',labelOutside:label.bottom<=screen.top+.5||label.top>=screen.bottom-.5,noDots:!document.querySelector('.hotspot'),chooser:!!document.querySelector('.lesson-sidebar [data-action="choose-lesson"]'),position:document.querySelector('.lesson-position').textContent.includes('LESSON '+(g.courseLessons.indexOf(c.l)+1)+' OF '+g.lessons.length),adjacent:panel.top-instruction.bottom>=0&&panel.top-instruction.bottom<20,hasNext:g.courseLessons.indexOf(c.l)===g.courseLessons.length-1||!!document.querySelector('.lesson-sidebar [data-action="next-lesson"]'),overflow:document.documentElement.scrollWidth>innerWidth};
})()`)}
app.whenReady().then(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));win=new BrowserWindow({width:1440,height:1000,useContentSize:true,show:false,webPreferences:{offscreen:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});
 win.webContents.on('console-message',e=>{if(e.level==='error'&&!e.message.includes('favicon'))report.errors.push(e.message)});
 await win.loadURL(`http://127.0.0.1:${server.address().port}/index.view.html`);await ready();await shot('desktop-home');check('Shared primary navigation is present with Tutorials active',await js(`document.querySelector('.nav-links a.active').textContent==='Tutorials'&&document.querySelector('.nav .brand').textContent==='GENESIS AI'`));
 const inventory=await js(`(()=>{const g=window.tutorialGuide;return {lessons:g.lessons.length,steps:g.lessons.reduce((n,l)=>n+l.steps.length,0),screens:Object.keys(g.manifest.screens).length,missingImages:g.lessons.flatMap(l=>[l.image,...l.steps.map(s=>s.screen)]).filter(s=>!g.manifest.screens[s]),missingAnchors:g.lessons.flatMap(l=>l.steps.map((s,i)=>({id:l.id,step:i+1,screen:s.screen,anchor:s.anchor,found:!!g.resolveAnchor(s)}))).filter(s=>!s.found)}})()`);
 Object.assign(report,{inventory,missingAnchors:inventory.missingAnchors});check('All referenced screenshot scenes exist',!inventory.missingImages.length,JSON.stringify(inventory.missingImages));check('Every step resolves to a visible screenshot control',!inventory.missingAnchors.length,JSON.stringify(inventory.missingAnchors));
 const ids=await js('window.tutorialGuide.lessons.map(l=>({id:l.id,steps:l.steps.length}))');
 check('Standard Genesis logo is loaded in the footer; shared primary bar supplies site branding',await js(`[...document.querySelectorAll('.brand-logo')].length===1&&[...document.querySelectorAll('.brand-logo')].every(i=>i.complete&&i.naturalWidth===192)&&!document.querySelector('.sigil')`));
 for(const l of ids){for(let n=1;n<=l.steps;n++){await route(l.id,n);const data=await js(`(()=>{const g=window.tutorialGuide.getCurrent();return {id:g?.l.id,step:g?.i,title:document.querySelector('#stepTitle')?.textContent,img:document.querySelector('.screen-stage img')?.getAttribute('src'),overflow:document.documentElement.scrollWidth>innerWidth}})()`);check(`Route ${l.id}/${n}`,data.id===l.id&&data.step===n-1&&!data.overflow,JSON.stringify(data));const layout=await inspectLesson();check(`Navigation and precise unobscured annotation ${l.id}/${n}`,Object.entries(layout).every(([k,v])=>k==='overflow'?!v:v),JSON.stringify(layout))}console.log('Verified '+l.id)}
 await route('model-controls',1);await js('window.scrollTo(0,370)');await shot('desktop-navigation');
 await route('parse-code',1);await js(`document.querySelector('[data-action="choose-lesson"]').click()`);
 check('Lab and quiz lesson retains full lesson chooser',await js(`document.querySelector('#dialog').open&&document.querySelectorAll('.picker-row').length===39&&document.querySelector('.picker-row[aria-current="page"]').dataset.lesson==='parse-code'`));await shot('desktop-chooser');
 await js(`document.querySelector('[data-action="picker-filter"][data-filter="remaining"]').click()`);check('Remaining filter excludes completed lessons',await js(`[...document.querySelectorAll('.picker-row')].every(e=>!window.tutorialGuide.getProgress().done.includes(e.dataset.lesson))`));
 await js(`document.querySelector('[data-action="picker-filter"][data-filter="all"]').click();document.querySelector('#pickerSearch').value='orb';document.querySelector('#pickerSearch').dispatchEvent(new Event('input',{bubbles:true}))`);check('Chooser search finds orb lesson',await js(`document.querySelectorAll('.picker-row').length===1&&document.querySelector('.picker-row').dataset.lesson==='orb'`));
 const priorDone=await js('window.tutorialGuide.getProgress().done.length');await js(`document.querySelector('.picker-row').click()`);await delay(80);check('Choosing another lesson changes route without marking it complete',await js(`window.tutorialGuide.getCurrent().l.id==='orb'&&!document.querySelector('#dialog').open&&window.tutorialGuide.getProgress().done.length===${priorDone}`));
 await js(`document.querySelector('[data-action="next-lesson"]').click()`);await delay(80);check('Right panel Next lesson follows course order',await js(`window.tutorialGuide.getCurrent().l.id===window.tutorialGuide.courseLessons[window.tutorialGuide.courseLessons.findIndex(l=>l.id==='orb')+1].id`));
 await js(`document.querySelector('[data-action="choose-lesson"]').click();document.querySelector('[data-action="full-library"]').click()`);await delay(80);check('Chooser full library clears old search and category filters',await js(`document.querySelectorAll('.lesson-card').length===39&&!document.querySelector('#dialog').open`));
 await route('missions',7);await js(`document.querySelector('[data-event="generate"]').click()`);check('Mission practice generates four clickable dependency nodes',await js(`document.querySelectorAll('.practice-node').length===4&&document.querySelector('.practice-node.table .node-state').textContent==='pending'`));
 await js(`document.querySelector('[data-event="problem"]').click()`);check('A failed source keeps its dependent table waiting',await js(`document.querySelector('.practice-node.rooms .node-state').textContent==='blocked'&&document.querySelector('.practice-node.table .node-state').textContent==='pending'&&document.querySelector('.practice-explanation').textContent.includes('cannot be opened')`));
 await js(`document.querySelector('[data-event="resolve"]').click()`);check('Checked replacement source makes table ready and retains recovery explanation',await js(`document.querySelector('.practice-node.table .node-state').textContent==='ready'&&document.querySelector('.practice-history').textContent.includes('old attempt remains')`));
 await js(`document.querySelector('[data-event="finish"]').click()`);check('Checked example still requires owner final review',await js(`document.querySelector('.practice-complete').textContent.includes('owner’s final review')`));await shot('desktop-mission-graph');
 await route('modes-controls',5);await shot('desktop-work-policy');
 await route('parse-code',4);await shot('desktop-parse-code');
 check('Pasted temperature overrides ordinary slider',await js(`document.querySelector('#labResult').textContent.includes('0.7')`));
 await js(`document.querySelector('#labMaster').click()`);check('Disabling pasted settings returns to slider',await js(`document.querySelector('#labResult').textContent.includes('0.3')`));
 await js(`document.querySelector('#labMaster').click();document.querySelector('#labChecked').click()`);check('Unchecking imported temperature returns to slider',await js(`document.querySelector('#labResult').textContent.includes('0.3')`));
 await route('vision',3);await js(`const h=document.querySelector('#labHelper');h.value='cloud';h.dispatchEvent(new Event('change',{bubbles:true}))`);check('Cloud helper clearly receives image',await js(`document.querySelector('#labResult').textContent.includes('goes to the cloud helper')`));
 await js(`document.querySelector('#labHelper').value='none';document.querySelector('#labHelper').dispatchEvent(new Event('change',{bubbles:true}))`);check('Text-only model without helper has no image route',await js(`document.querySelector('#labResult').textContent.includes('cannot describe the pixels')`));
 await js(`document.querySelector('#labPrimary').value='vision';document.querySelector('#labPrimary').dispatchEvent(new Event('change',{bubbles:true}))`);check('Vision main model can read image directly',await js(`document.querySelector('#labResult').textContent.includes('same model answers')`));
 await js(`document.querySelector('#labPrimary').value='text';document.querySelector('#labHelper').value='local';document.querySelector('#labHelper').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('#labPrimary').dispatchEvent(new Event('change',{bubbles:true}))`);await shot('desktop-vision');
 await route('interface',1);await js(`document.querySelector('[data-action="next"]').click()`);await delay(60);check('Next button advances one step',await js('window.tutorialGuide.getCurrent().i===1'));
 await js(`document.querySelector('[data-action="previous"]').click()`);await delay(60);check('Back button returns one step',await js('window.tutorialGuide.getCurrent().i===0'));
 await js(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}))`);await delay(60);check('Keyboard right arrow advances step',await js('window.tutorialGuide.getCurrent().i===1'));
 const hot=await js(`(()=>{const e=[...document.querySelectorAll('.screen-steps button')].find(e=>!e.hasAttribute('aria-current'));if(!e)return null;const n=Number(e.dataset.step);e.click();return n})()`);await delay(80);check('Labelled screenshot control opens its corresponding step',hot!==null&&await js(`window.tutorialGuide.getCurrent().i===${hot}`));
 await js(`document.querySelector('[data-action="zoom"]').click()`);check('Full-size screenshot opens in modal',await js(`document.querySelector('#dialog').open&&document.querySelector('.zoom-body img').naturalWidth===1600`));await js(`document.querySelector('[data-action="close"]').click()`);check('Modal closes',await js(`!document.querySelector('#dialog').open`));
 await js(`document.querySelector('[data-action="glossary"]').click();document.querySelector('#wordSearch').value='token';document.querySelector('#wordSearch').dispatchEvent(new Event('input',{bubbles:true}))`);check('Glossary search finds a simple definition',await js(`document.querySelector('#wordList').textContent.includes('small piece of text')`));await js(`document.querySelector('[data-action="close"]').click()`);
 await route('welcome',1);await js(`document.querySelector('[data-action="quiz"][data-answer="1"]').click()`);check('Quiz explains wrong choice',await js(`document.querySelector('#quizFeedback').textContent.startsWith('Try another choice')`));await js(`document.querySelector('[data-action="quiz"][data-answer="0"]').click()`);check('Quiz explains correct choice',await js(`document.querySelector('#quizFeedback').textContent.startsWith('Exactly')`));
 await route('backup-data',5);await js(`document.querySelector('[data-action="next"]').click()`);check('Completion saves tutorial progress',await js(`window.tutorialGuide.getProgress().done.includes('backup-data')`));await new Promise(resolve=>{win.webContents.once('did-finish-load',resolve);win.webContents.reload()});await ready();check('Progress survives reload',await js(`window.tutorialGuide.getProgress().done.includes('backup-data')`));
 await js(`location.hash='#library'`);await delay(80);await js(`const q=document.querySelector('#lessonSearch');q.value='Whisper';q.dispatchEvent(new Event('input',{bubbles:true}))`);check('Full-text lesson search narrows cards',await js(`document.querySelectorAll('.lesson-card').length>0&&document.querySelectorAll('.lesson-card').length<window.tutorialGuide.lessons.length`));await js(`document.querySelector('#lessonSearch').value='';document.querySelector('#lessonSearch').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('[data-filter="models"]').click()`);check('Category filter shows only model lessons',await js(`document.querySelectorAll('.catalog-group').length===1&&document.querySelectorAll('.lesson-card').length===window.tutorialGuide.lessons.filter(l=>l.group==='models').length`));
 // The profile and server are isolated: clear only this QA browser's guide progress.
 await js(`document.querySelector('[data-action="reset"]').click();document.querySelector('[data-action="confirm-reset"]').click()`);await delay(80);
 const course=await js('window.tutorialGuide.courseLessons.map(l=>({id:l.id,steps:l.steps.length}))');await route(course[0].id,1);
 let clicks=0;for(let k=0;k<course.length;k++){const l=course[k];for(let n=1;n<=l.steps;n++){const following=n<l.steps?{id:l.id,n:n+1}:course[k+1]?{id:course[k+1].id,n:1}:{id:l.id,n};await clickAdvance(following.id,following.n);clicks++;check(`Continuous Next journey ${l.id}/${n}`,await js(`window.tutorialGuide.getCurrent().l.id===${JSON.stringify(following.id)}&&window.tutorialGuide.getCurrent().i===${following.n-1}`))}}
 check('One Next journey completes every lesson through the final step',clicks===inventory.steps&&await js(`window.tutorialGuide.getProgress().done.length===39&&document.querySelector('.course-end').textContent.includes('whole guide')&&document.querySelector('[data-action="next"]').disabled&&!document.querySelector('[data-action="next-lesson"]')`));
 await js(`document.querySelector('[data-action="choose-lesson"]').click();document.querySelector('[data-action="picker-filter"][data-filter="done"]').click()`);check('Final lesson still offers all completed lessons',await js(`document.querySelectorAll('.picker-row').length===39&&[...document.querySelectorAll('.picker-status')].every(e=>e.textContent.includes('Completed'))`));
 await js(`document.querySelector('[data-action="picker-filter"][data-filter="remaining"]').click()`);check('Remaining filter reports whole guide complete',await js(`document.querySelector('#pickerList').textContent.includes('Every lesson is complete')`));await js(`document.querySelector('[data-action="close"]').click()`);
 win.setContentSize(390,844);await js(`location.hash=''`);await delay(250);await shot('mobile-home');const mobile=await js(`({width:innerWidth,document:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect();return r.right>innerWidth+1||r.left< -1}).slice(0,12).map(e=>({tag:e.tagName,class:e.className,right:e.getBoundingClientRect().right,left:e.getBoundingClientRect().left}))})`);check('Mobile landing does not overflow horizontally',mobile.document<=mobile.width,JSON.stringify(mobile));
 for(const l of ids){for(let n=1;n<=l.steps;n++){await route(l.id,n);const layout=await inspectLesson();check(`Mobile layout and annotation ${l.id}/${n}`,Object.entries(layout).every(([k,v])=>k==='overflow'?!v:v),JSON.stringify(layout))}}await route('orb',3);await shot('mobile-orb');await route('parse-code',4);await shot('mobile-parse-code');
 await route('missions',7);await shot('mobile-mission');await js(`document.querySelector('[data-action="choose-lesson"]').click()`);check('Mobile chooser exposes every lesson without horizontal overflow',await js(`document.querySelectorAll('.picker-row').length===39&&document.documentElement.scrollWidth<=innerWidth&&document.querySelector('#dialog').scrollWidth<=document.querySelector('#dialog').clientWidth`));await shot('mobile-chooser');await js(`document.querySelector('[data-action="close"]').click()`);
 const broken=await js(`[...document.images].filter(i=>i.complete&&!i.naturalWidth).map(i=>i.src)`);check('Visible images load',!broken.length,JSON.stringify(broken));check('No renderer exceptions',!report.errors.length,report.errors.join('\n'));
 const scenes=await js(`(()=>{const g=window.tutorialGuide,plain=s=>s.split('**').join('');return {date:g.manifest.captured,origin:g.manifest.origin,status:'Tutorial lesson assets. Videos have not been produced.',overlays:'Separate HTML/text layers, transparent yellow rectangles and connecting lines without arrowheads. Original PNGs are kept clean.',lessons:g.courseLessons.map(l=>({id:l.id,title:l.title,group:l.group,coursePosition:g.courseLessons.indexOf(l)+1,prerequisites:l.needs,steps:l.steps.map((s,i)=>{const a=g.resolveAnchor(s),m=g.manifest.screens[s.screen];return {step:i+1,title:s.title,screenshot:'screens/'+m.file,screenshotSha256:m.sha256,width:m.width,height:m.height,anchor:{label:s.anchor,x:a.x,y:a.y,width:a.w,height:a.h,xPercent:100*a.x/m.width,yPercent:100*a.y/m.height},annotation:g.annotation(l,i),narrationDraft:plain(s.body),checkpoint:plain(s.check),tip:plain(s.tip)}})}))}})()`);
 fs.writeFileSync(path.join(root,'assets/scenes.json'),JSON.stringify(scenes,null,2));
 check('Reusable scene catalog includes every tutorial step',scenes.lessons.reduce((n,l)=>n+l.steps.length,0)===inventory.steps);
 fs.writeFileSync(path.join(evidence,'verification.json'),JSON.stringify(report,null,2));console.log('Passed '+report.assertions.length+' assertions. '+inventory.lessons+' lessons; '+inventory.steps+' steps; '+inventory.screens+' screens. Missing anchors: '+report.missingAnchors.length);
 win.destroy();server.close();app.quit();
}).catch(e=>{report.failure=e.stack;fs.writeFileSync(path.join(evidence,'verification.json'),JSON.stringify(report,null,2));console.error(e.stack);server.close();app.exit(1)});
